<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<c:set var="ctp" value="${pageContext.request.contextPath}"/>
<p>제1조&nbsp;정의</p>
<p>본&nbsp;약관의&nbsp;주요&nbsp;용어는&nbsp;아래와&nbsp;같이&nbsp;정의합니다.</p>
<p>①&nbsp;&ldquo;Mood&nbsp;Ritual몰&rdquo;은&nbsp;Mood&nbsp;Ritual이&nbsp;운영하는&nbsp;공식&nbsp;온라인&nbsp;쇼핑몰을&nbsp;말합니다.</p>
<p>②&nbsp;&quot;서비스&quot;란&nbsp;Mood&nbsp;Ritual&nbsp;몰&nbsp;사이트&nbsp;및&nbsp;사이트&nbsp;관련&nbsp;각종&nbsp;서비스를&nbsp;말합니다.</p>
<p>③&nbsp;&quot;이용자&quot;란&nbsp;사이트에&nbsp;접속하여&nbsp;이&nbsp;약관에&nbsp;따라&nbsp;Mood&nbsp;Ritual&nbsp;몰이&nbsp;제공하는&nbsp;서비스를&nbsp;받는&nbsp;&quot;회원&quot;과&nbsp;&ldquo;비회원&rdquo;을&nbsp;말합니다.</p>
<p>④&nbsp;&quot;회원&quot;은&nbsp;Mood&nbsp;Ritual&nbsp;몰에&nbsp;개인&nbsp;정보를&nbsp;제공하여&nbsp;회원&nbsp;등록을&nbsp;한&nbsp;자로서,&nbsp;회원&nbsp;전용&nbsp;서비스를&nbsp;이용할&nbsp;수&nbsp;있는&nbsp;자를&nbsp;말합니다.</p>
<p>⑤&nbsp;&ldquo;비회원&rdquo;은&nbsp;회원에&nbsp;가입하지&nbsp;않고&nbsp;Mood&nbsp;Ritual&nbsp;몰이&nbsp;제공하는&nbsp;서비스를&nbsp;이용하는&nbsp;자를&nbsp;말합니다.</p>
<p>⑥&nbsp;이&nbsp;약관에서&nbsp;정하지&nbsp;아니한&nbsp;내용과&nbsp;이&nbsp;약관의&nbsp;해석에&nbsp;관하여는&nbsp;전자상거래&nbsp;등에서의&nbsp;소비자&nbsp;보호에&nbsp;관한&nbsp;법률,&nbsp;약관의&nbsp;규제&nbsp;등에&nbsp;관한&nbsp;법률,&nbsp;공정거래위원회가&nbsp;정하는&nbsp;전자상거래&nbsp;등에서의&nbsp;소비자&nbsp;보호지침&nbsp;및&nbsp;관계법령&nbsp;또는&nbsp;상관례에&nbsp;따릅니다.</p>
<p>&nbsp;</p>
<p>제2조&nbsp;개인&nbsp;정보&nbsp;보호</p>
<p>회사의&nbsp;개인정보취급방침에&nbsp;대한&nbsp;이해를&nbsp;돕기&nbsp;위하여&nbsp;회사의&nbsp;개인정보취급방침을&nbsp;참조하시기&nbsp;바랍니다.&nbsp;또한,&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;고객의&nbsp;개인정보처리에&nbsp;대하여&nbsp;동의를&nbsp;받고&nbsp;있으며,&nbsp;개인정보처리방침이&nbsp;변경되는&nbsp;경우에도&nbsp;위와&nbsp;같습니다.</p>
<p>&nbsp;</p>
<p>제&nbsp;3조&nbsp;약관의&nbsp;변경</p>
<p>①&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;약관의&nbsp;내용,&nbsp;상호,&nbsp;대표자&nbsp;성명,&nbsp;영업소재지&nbsp;(소비자의&nbsp;불만을&nbsp;처리할&nbsp;수&nbsp;있는&nbsp;곳의&nbsp;주소를&nbsp;포함),&nbsp;전화번호,&nbsp;전자우편번호,&nbsp;사업자&nbsp;등록번호,&nbsp;통신판매업&nbsp;신고번호를&nbsp;이용자가&nbsp;확인할&nbsp;수&nbsp;있도록,&nbsp;Mood&nbsp;Ritual&nbsp;몰&nbsp;초기&nbsp;화면에&nbsp;게시합니다.&nbsp;다만,&nbsp;약관의&nbsp;내용은&nbsp;연결화면을&nbsp;통하여&nbsp;볼&nbsp;수&nbsp;있도록&nbsp;할&nbsp;수&nbsp;있습니다.</p>
<p>②&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;이용자가&nbsp;약관에&nbsp;동의하기에&nbsp;앞서,&nbsp;약관에&nbsp;정해져&nbsp;있는&nbsp;내용&nbsp;중&nbsp;청약철회,&nbsp;배송책임,&nbsp;환불조건&nbsp;등과&nbsp;같은&nbsp;중요한&nbsp;내용을&nbsp;이용자가&nbsp;이해할&nbsp;수&nbsp;있도록&nbsp;별도의&nbsp;연결화면으로&nbsp;제공하여&nbsp;이용자의&nbsp;확인을&nbsp;구해야&nbsp;합니다.</p>
<p>③&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;전자상거래&nbsp;등에서의&nbsp;소비자보호에&nbsp;관한&nbsp;법률,&nbsp;약관의&nbsp;규제에&nbsp;관한&nbsp;법률,&nbsp;전자문서&nbsp;및&nbsp;전자거래기본법,&nbsp;전자거래금융법,&nbsp;전자서명법,&nbsp;정보통신망&nbsp;이용촉진&nbsp;및&nbsp;정보보호&nbsp;등에&nbsp;관한&nbsp;법률,&nbsp;방문판매&nbsp;등에&nbsp;관한&nbsp;법률,&nbsp;소비자보호법&nbsp;등&nbsp;관련법을&nbsp;위배하지&nbsp;않는&nbsp;범위에서&nbsp;이&nbsp;약관을&nbsp;개정할&nbsp;수&nbsp;있습니다.</p>
<p>④&nbsp;Mood&nbsp;Ritual&nbsp;몰이&nbsp;약관을&nbsp;개정할&nbsp;경우에는&nbsp;적용일자&nbsp;및&nbsp;개정사유를&nbsp;명시하여&nbsp;현행약관과&nbsp;함께&nbsp;몰의&nbsp;초기화면에&nbsp;그&nbsp;적용일자&nbsp;7일&nbsp;이전부터&nbsp;적용일자&nbsp;전일까지&nbsp;공지합니다.&nbsp;다만,&nbsp;이용자에게&nbsp;불리하게&nbsp;약관내용을&nbsp;변경하는&nbsp;경우에는&nbsp;최소한&nbsp;30일&nbsp;이상의&nbsp;사전&nbsp;유예기간을&nbsp;두고&nbsp;공지합니다.&nbsp;이&nbsp;경우&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;개정&nbsp;전&nbsp;내용과&nbsp;개정&nbsp;후&nbsp;내용을&nbsp;명확하게&nbsp;비교하여&nbsp;이용자가&nbsp;알기&nbsp;쉽도록&nbsp;표시합니다.</p>
<p>⑤&nbsp;Mood&nbsp;Ritual&nbsp;몰이&nbsp;약관을&nbsp;개정할&nbsp;경우에는&nbsp;그&nbsp;개정약관은&nbsp;그&nbsp;적용일자&nbsp;이후에&nbsp;체결되는&nbsp;계약에만&nbsp;적용되고&nbsp;그&nbsp;이전에&nbsp;이미&nbsp;체결된&nbsp;계약에&nbsp;대해서는&nbsp;개정&nbsp;전의&nbsp;약관조항이&nbsp;그대로&nbsp;적용됩니다.&nbsp;다만&nbsp;이미&nbsp;계약을&nbsp;체결한&nbsp;이용자가&nbsp;개정약관&nbsp;조항의&nbsp;적용을&nbsp;받기를&nbsp;원하는&nbsp;뜻을&nbsp;본조&nbsp;제4항에&nbsp;의한&nbsp;개정약관의&nbsp;공지기간&nbsp;내에&nbsp;Mood&nbsp;Ritual&nbsp;몰에&nbsp;송신하여&nbsp;Mood&nbsp;Ritual&nbsp;몰의&nbsp;동의를&nbsp;받은&nbsp;경우에는&nbsp;개정약관&nbsp;조항이&nbsp;적용됩니다.</p>
<p>⑥&nbsp;이&nbsp;약관에서&nbsp;정하지&nbsp;아니한&nbsp;내용과&nbsp;이&nbsp;약관의&nbsp;해석에&nbsp;관하여&nbsp;전자상거래&nbsp;등에서의&nbsp;소비자보호에&nbsp;관한&nbsp;법률,&nbsp;약관의&nbsp;규제&nbsp;등에&nbsp;관한&nbsp;법률,&nbsp;공정거래위원회가&nbsp;정하는&nbsp;전자상거래&nbsp;등에서의&nbsp;소비자&nbsp;보호지침&nbsp;및&nbsp;관계법령&nbsp;또는&nbsp;상관례에&nbsp;따릅니다.</p>
<p>&nbsp;</p>
<p>제4조&nbsp;이용자에게&nbsp;제공된&nbsp;서비스&nbsp;취소</p>
<p>본&nbsp;사이트에서&nbsp;제공되는&nbsp;제품과&nbsp;서비스&nbsp;및&nbsp;회사가&nbsp;이용자에게&nbsp;제공할&nbsp;수&nbsp;있는&nbsp;제품&nbsp;등의&nbsp;샘플&nbsp;일체는&nbsp;개인&nbsp;용도에&nbsp;국한됩니다.&nbsp;이용자는&nbsp;회사로부터&nbsp;구매하거나&nbsp;달리&nbsp;수령한&nbsp;모든&nbsp;제품,&nbsp;서비스&nbsp;또는&nbsp;동&nbsp;제품&nbsp;등의&nbsp;샘플을&nbsp;상업적인&nbsp;용도로&nbsp;판매&nbsp;또는&nbsp;재판매&nbsp;할&nbsp;수&nbsp;없습니다.&nbsp;회사는&nbsp;본&nbsp;약관을&nbsp;위반하는&nbsp;결과를&nbsp;초래할&nbsp;수&nbsp;있다고&nbsp;판단하는&nbsp;경우,&nbsp;이용자에게&nbsp;통지한&nbsp;후&nbsp;모든&nbsp;주문&nbsp;또는&nbsp;이용자에게&nbsp;제공된&nbsp;제품이나&nbsp;서비스를&nbsp;취소하거나&nbsp;그&nbsp;제품의&nbsp;수량을&nbsp;감축할&nbsp;수&nbsp;있는&nbsp;권리를&nbsp;보유합니다.</p>
<p>&nbsp;</p>
<p>제5조&nbsp;구매&nbsp;신청</p>
<p>이용자는&nbsp;Mood&nbsp;Ritual&nbsp;몰에서&nbsp;다음&nbsp;또는&nbsp;이와&nbsp;유사한&nbsp;방법에&nbsp;의하여&nbsp;구매를&nbsp;신청하며,&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;이용자가&nbsp;구매신청을&nbsp;함에&nbsp;있어서&nbsp;다음의&nbsp;각&nbsp;내용을&nbsp;알기&nbsp;쉽게&nbsp;제공하여야&nbsp;합니다.</p>
<p>①&nbsp;재화&nbsp;등의&nbsp;검색&nbsp;및&nbsp;선택</p>
<p>②&nbsp;성명,&nbsp;주소,&nbsp;전화번호,&nbsp;이메일&nbsp;주소&nbsp;(또는&nbsp;휴대전화번호)&nbsp;등의&nbsp;입력</p>
<p>③&nbsp;이&nbsp;약관에&nbsp;동의하고&nbsp;위&nbsp;3호의&nbsp;사항을&nbsp;확인하거나&nbsp;거부하는&nbsp;표시&nbsp;(예:&nbsp;마우스&nbsp;클릭)</p>
<p>④&nbsp;재화&nbsp;등의&nbsp;구매신청&nbsp;및&nbsp;이에&nbsp;관한&nbsp;확인&nbsp;또는&nbsp;Mood&nbsp;Ritual&nbsp;몰의&nbsp;확인에&nbsp;대한&nbsp;동의</p>
<p>⑤&nbsp;결제방법의&nbsp;선택</p>
<p>&nbsp;</p>
<p>제6조&nbsp;구매계약의&nbsp;성립</p>
<p>①&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;제5조&nbsp;구매신청에&nbsp;대하여&nbsp;다음&nbsp;각&nbsp;호에&nbsp;해당하면&nbsp;승낙하지&nbsp;않을&nbsp;수&nbsp;있습니다.</p>
<p>신청&nbsp;내용에&nbsp;허위,&nbsp;기재누락,&nbsp;오기가&nbsp;있는&nbsp;경우</p>
<p>상행위(재판매)를&nbsp;목적으로&nbsp;구매하는&nbsp;거래이거나,&nbsp;거래&nbsp;정황상&nbsp;상행위(재판매)를&nbsp;목적으로&nbsp;한&nbsp;구매로&nbsp;판단되는&nbsp;경우</p>
<p>기타&nbsp;구매신청을&nbsp;승낙하는&nbsp;것이&nbsp;Mood&nbsp;Ritual&nbsp;몰에&nbsp;기술적인&nbsp;문제를&nbsp;발생시키는&nbsp;경우</p>
<p>②&nbsp;Mood&nbsp;Ritual&nbsp;몰의&nbsp;승낙이&nbsp;제8조의&nbsp;수신확인&nbsp;통지형태로&nbsp;이용자에게&nbsp;도달한&nbsp;시점에&nbsp;구매계약이&nbsp;성립한&nbsp;것으로&nbsp;봅니다.</p>
<p>③&nbsp;Mood&nbsp;Ritual&nbsp;몰의&nbsp;승낙의&nbsp;의사표시에는&nbsp;이용자의&nbsp;구매신청에&nbsp;대한&nbsp;확인&nbsp;및&nbsp;판매가능&nbsp;여부,&nbsp;구매신청의&nbsp;정정&nbsp;취소&nbsp;등에&nbsp;관한&nbsp;정보&nbsp;등을&nbsp;포함하여야&nbsp;합니다.</p>
<p>&nbsp;</p>
<p>제7조&nbsp;지급방법</p>
<p>Mood&nbsp;Ritual&nbsp;몰에서&nbsp;구매한&nbsp;제품에&nbsp;대한&nbsp;대금지급은&nbsp;신용카드&nbsp;등의&nbsp;각종&nbsp;카드&nbsp;결제로&nbsp;할&nbsp;수&nbsp;있습니다.&nbsp;단,&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;이용자의&nbsp;지급방법에&nbsp;대하여&nbsp;재화&nbsp;등의&nbsp;대금에&nbsp;어떠한&nbsp;명목의&nbsp;수수료도&nbsp;추가하여&nbsp;징수할&nbsp;수&nbsp;없습니다.</p>
<p>&nbsp;</p>
<p>제8조&nbsp;수신확인통지/구매신청&nbsp;변경&nbsp;및&nbsp;취소</p>
<p>Mood&nbsp;Ritual&nbsp;몰은&nbsp;이용자의&nbsp;구매신청이&nbsp;있는&nbsp;경우&nbsp;이용자에게&nbsp;수신확인&nbsp;통지를&nbsp;합니다.&nbsp;수신확인&nbsp;통지를&nbsp;받은&nbsp;이용자는&nbsp;의사표시의&nbsp;불일치&nbsp;등이&nbsp;있는&nbsp;경우에는&nbsp;수신확인통지를&nbsp;받은&nbsp;후&nbsp;즉시&nbsp;구매신청&nbsp;변경&nbsp;및&nbsp;취소를&nbsp;요청할&nbsp;수&nbsp;있고,&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;배송&nbsp;전에&nbsp;이용자의&nbsp;요청이&nbsp;있는&nbsp;경우에는&nbsp;지체&nbsp;없이&nbsp;그&nbsp;요청에&nbsp;따라&nbsp;처리하여야&nbsp;합니다.&nbsp;다만,&nbsp;이미&nbsp;대금을&nbsp;지불한&nbsp;경우에는&nbsp;제&nbsp;11조의&nbsp;청약철회&nbsp;등에&nbsp;관한&nbsp;규정에&nbsp;따릅니다.</p>
<p>&nbsp;</p>
<p>제9조&nbsp;재화&nbsp;등의&nbsp;공급</p>
<p>①&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;이용자와&nbsp;재화&nbsp;등의&nbsp;공급시기에&nbsp;관하여&nbsp;별도의&nbsp;약정이&nbsp;없는&nbsp;이상,&nbsp;이용자가&nbsp;청약을&nbsp;한&nbsp;날로부터&nbsp;7일&nbsp;이내에&nbsp;재화&nbsp;등을&nbsp;배송할&nbsp;수&nbsp;있도록&nbsp;주문제작,&nbsp;포장&nbsp;등&nbsp;기타의&nbsp;필요한&nbsp;조치를&nbsp;취합니다.&nbsp;다만,&nbsp;Mood&nbsp;Ritual&nbsp;몰이&nbsp;이미&nbsp;재화&nbsp;등의&nbsp;대금의&nbsp;전부&nbsp;또는&nbsp;일부를&nbsp;받은&nbsp;경우에는&nbsp;대금의&nbsp;전부&nbsp;또는&nbsp;일부를&nbsp;받은&nbsp;날부터&nbsp;3영업일&nbsp;이내에&nbsp;조치를&nbsp;취합니다.&nbsp;이때&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;이용자가&nbsp;재화&nbsp;등의&nbsp;공급&nbsp;절차&nbsp;및&nbsp;진행&nbsp;사항을&nbsp;확인&nbsp;할&nbsp;수&nbsp;있도록&nbsp;적절한&nbsp;조치를&nbsp;합니다.</p>
<p>②&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;이용자가&nbsp;구매한&nbsp;제품에&nbsp;대해&nbsp;배송수단,&nbsp;수단별&nbsp;배송비용&nbsp;부담자,&nbsp;수단별&nbsp;배송기간&nbsp;등을&nbsp;명시합니다.</p>
<p>제10조&nbsp;환급</p>
<p>Mood&nbsp;Ritual&nbsp;몰은&nbsp;이용자가&nbsp;구매&nbsp;신청한&nbsp;재화&nbsp;등이&nbsp;품절&nbsp;등의&nbsp;사유로&nbsp;인도&nbsp;또는&nbsp;제공을&nbsp;할&nbsp;수&nbsp;없을&nbsp;때에는&nbsp;지체&nbsp;없이&nbsp;그&nbsp;사유를&nbsp;이용자에게&nbsp;통지하고&nbsp;사전에&nbsp;재화&nbsp;등의&nbsp;대금을&nbsp;받은&nbsp;경우에는&nbsp;3영업일&nbsp;이내에&nbsp;환급하거나&nbsp;환급에&nbsp;필요한&nbsp;조치를&nbsp;취합니다.&nbsp;다만,&nbsp;일시품절의&nbsp;경우&nbsp;구매자가&nbsp;동의한다면&nbsp;대금을&nbsp;환급하지&nbsp;않고&nbsp;제품이&nbsp;입고된&nbsp;후에&nbsp;배송할&nbsp;수&nbsp;있습니다.</p>
<p>&nbsp;</p>
<p>제11조&nbsp;청약철회</p>
<p>구매자는&nbsp;&rsquo;전자상거래&nbsp;등에서의&nbsp;소비자보호에&nbsp;관한&nbsp;법률&rsquo;&nbsp;제17조에&nbsp;의해,&nbsp;구매한&nbsp;상품을&nbsp;배송&nbsp;받은&nbsp;후&nbsp;30일&nbsp;이내에&nbsp;반품&nbsp;또는&nbsp;교환을&nbsp;요청할&nbsp;수&nbsp;있으며,&nbsp;반품에&nbsp;관한&nbsp;일반적인&nbsp;사항은&nbsp;&rsquo;전자상거래&nbsp;등에서의&nbsp;소비자보호에&nbsp;관한&nbsp;법률&rsquo;&nbsp;등&nbsp;관련&nbsp;법령이&nbsp;판매자가&nbsp;제시한&nbsp;조건보다&nbsp;우선합니다.&nbsp;단,&nbsp;다음&nbsp;각&nbsp;호의&nbsp;경우에는&nbsp;구매자가&nbsp;반품&nbsp;또는&nbsp;교환을&nbsp;요청할&nbsp;수&nbsp;없습니다.</p>
<p>이용자에게&nbsp;책임&nbsp;있는&nbsp;사유로&nbsp;재화&nbsp;등이&nbsp;멸실&nbsp;또는&nbsp;훼손된&nbsp;경우.&nbsp;단,&nbsp;재화&nbsp;등의&nbsp;내용&nbsp;확인을&nbsp;위하여&nbsp;박스포장&nbsp;등을&nbsp;훼손한&nbsp;경우는&nbsp;제외합니다.&nbsp;(예)&nbsp;뚜껑을&nbsp;열어&nbsp;내용물을&nbsp;확인한&nbsp;경우&nbsp;교환이&nbsp;어려울&nbsp;수&nbsp;있습니다.</p>
<p>이용자의&nbsp;사용&nbsp;또는&nbsp;일부&nbsp;소비에&nbsp;의하여&nbsp;재화&nbsp;등의&nbsp;가치가&nbsp;현저히&nbsp;감소한&nbsp;경우</p>
<p>시간의&nbsp;경과에&nbsp;의하여&nbsp;재판매가&nbsp;곤란할&nbsp;정도로&nbsp;재화&nbsp;등의&nbsp;가치가&nbsp;현저히&nbsp;감소한&nbsp;경우</p>
<p>같은&nbsp;성능을&nbsp;지닌&nbsp;제품&nbsp;등으로&nbsp;복제가&nbsp;가능한&nbsp;경우&nbsp;그&nbsp;원본인&nbsp;제품&nbsp;등의&nbsp;포장&nbsp;등을&nbsp;훼손한&nbsp;경우</p>
<p>기타&nbsp;구매자가&nbsp;환불&nbsp;또는&nbsp;교환을&nbsp;요청할&nbsp;수&nbsp;없는&nbsp;합리적인&nbsp;사유가&nbsp;있는&nbsp;경우</p>
<p>제12조&nbsp;청약철회&nbsp;등의&nbsp;효과</p>
<p>①&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;이용자로부터&nbsp;재화&nbsp;등을&nbsp;반환&nbsp;받은&nbsp;경우&nbsp;영업일&nbsp;3일&nbsp;이내에&nbsp;환급하거나&nbsp;환급에&nbsp;필요한&nbsp;조치를&nbsp;취합니다.</p>
<p>②&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;위&nbsp;대금을&nbsp;환급함에&nbsp;있어서&nbsp;이용자가&nbsp;신용카드&nbsp;등의&nbsp;결제수단으로&nbsp;재화&nbsp;등의&nbsp;대금을&nbsp;지급한&nbsp;때에는&nbsp;지체&nbsp;없이&nbsp;당해&nbsp;결제수단을&nbsp;제공한&nbsp;사업자로&nbsp;하여금&nbsp;재화&nbsp;등의&nbsp;대금의&nbsp;청구를&nbsp;정지&nbsp;또는&nbsp;취소하도록&nbsp;요청합니다.</p>
<p>③&nbsp;청약철회&nbsp;등의&nbsp;경우&nbsp;공급받은&nbsp;재화&nbsp;등의&nbsp;반환에&nbsp;필요한&nbsp;비용은&nbsp;이용자가&nbsp;부담합니다.&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;이용자에게&nbsp;청약철회&nbsp;등을&nbsp;이유로&nbsp;위약금&nbsp;또는&nbsp;손해배상을&nbsp;청구하지&nbsp;않습니다.&nbsp;다만,&nbsp;재화&nbsp;등의&nbsp;내용이&nbsp;표시/광고&nbsp;내용과&nbsp;다르거나&nbsp;계약&nbsp;내용과&nbsp;다르게&nbsp;이행되어&nbsp;청약철회&nbsp;등을&nbsp;하는&nbsp;경우&nbsp;재화&nbsp;등의&nbsp;반환에&nbsp;필요한&nbsp;비용은&nbsp;Mood&nbsp;Ritual&nbsp;몰이&nbsp;부담합니다.</p>
<p>④&nbsp;이용자가&nbsp;재화&nbsp;등을&nbsp;제공받을&nbsp;때&nbsp;발송비를&nbsp;부담한&nbsp;경우에&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;청약철회&nbsp;시&nbsp;그&nbsp;비용을&nbsp;누가&nbsp;부담하는지를&nbsp;이용자가&nbsp;알기&nbsp;쉽도록&nbsp;명확하게&nbsp;표시합니다.</p>
<p>제13조&nbsp;정보의&nbsp;정확성</p>
<p>회사는&nbsp;본&nbsp;사이트에&nbsp;제품을&nbsp;게재함에&nbsp;있어서&nbsp;가능한&nbsp;한&nbsp;정확한&nbsp;정보를&nbsp;제공하고자&nbsp;합니다.&nbsp;그러나,&nbsp;관련&nbsp;법률의&nbsp;허용범위&nbsp;내에서,&nbsp;제품설명,&nbsp;색상,&nbsp;정보&nbsp;또는&nbsp;본&nbsp;사이트에서&nbsp;제공되는&nbsp;기타&nbsp;컨텐츠의&nbsp;정확성,&nbsp;완전성,&nbsp;신뢰성,&nbsp;유효성,&nbsp;무하자&nbsp;및&nbsp;무오류를&nbsp;보장하지&nbsp;아니합니다.</p>
<p>&nbsp;</p>
<p>제14조&nbsp;지적&nbsp;재산</p>
<p>본&nbsp;사이트에서&nbsp;이용할&nbsp;수&nbsp;있는&nbsp;모든&nbsp;정보와&nbsp;컨텐츠&nbsp;및&nbsp;&apos;look&nbsp;and&nbsp;feel&apos;의&nbsp;요소들&nbsp;(상표,&nbsp;로고,&nbsp;서비스마크,&nbsp;텍스트,&nbsp;그래픽,&nbsp;로고,&nbsp;버튼&nbsp;아이콘,&nbsp;이미지,&nbsp;오디오&nbsp;클립,&nbsp;데이터&nbsp;편집물,&nbsp;소프트웨어&nbsp;및&nbsp;위&nbsp;각&nbsp;요소의&nbsp;편집물&nbsp;및&nbsp;결합물을&nbsp;포함하며&nbsp;이에&nbsp;한정되지&nbsp;않습니다,&nbsp;통칭하여&nbsp;&apos;본&nbsp;컨텐츠&apos;)&nbsp;은&nbsp;회사&nbsp;및&nbsp;회사의&nbsp;계열사,&nbsp;파트너&nbsp;또는&nbsp;라이센서의&nbsp;재산이며,&nbsp;저작권과&nbsp;상표권을&nbsp;규율하는&nbsp;관계&nbsp;법률들에&nbsp;의하여&nbsp;보호받습니다.</p>
<p>관련&nbsp;법률에&nbsp;의하여&nbsp;요구되는&nbsp;경우를&nbsp;제외하고,&nbsp;본&nbsp;컨텐츠&nbsp;또는&nbsp;본&nbsp;사이트의&nbsp;어떠한&nbsp;부분도&nbsp;회사의&nbsp;명시적인&nbsp;사전&nbsp;서면동의&nbsp;없이는&nbsp;전체&nbsp;또는&nbsp;부문을&nbsp;막론하고,&nbsp;영리&nbsp;목적으로&nbsp;사용,&nbsp;재생,&nbsp;복제,&nbsp;복사,&nbsp;판매,&nbsp;재판매,&nbsp;접속,&nbsp;수정&nbsp;또는&nbsp;달리&nbsp;이용될&nbsp;수&nbsp;없습니다.</p>
<p>&nbsp;</p>
<p>제15조&nbsp;제한적&nbsp;이용허락</p>
<p>①&nbsp;회사는&nbsp;이용자가&nbsp;본&nbsp;사이트에&nbsp;접속하여&nbsp;개인&nbsp;용도로&nbsp;본&nbsp;사이트를&nbsp;이용할&nbsp;수&nbsp;있는&nbsp;제한적이고&nbsp;취소가능하며&nbsp;비독점적인&nbsp;이용권한을&nbsp;이용자에게&nbsp;허용합니다.&nbsp;이&nbsp;제한적&nbsp;이용권한은&nbsp;다음&nbsp;각&nbsp;호의&nbsp;권리를&nbsp;포함하지&nbsp;않습니다.&nbsp;이용자는&nbsp;본&nbsp;사이트상&nbsp;또는&nbsp;본&nbsp;사이트에&nbsp;첨부되거나&nbsp;그에&nbsp;포함되는&nbsp;모든&nbsp;권리에&nbsp;관한&nbsp;통지를&nbsp;변경&nbsp;없이&nbsp;보유하여야&nbsp;합니다.</p>
<p>본&nbsp;사이트&nbsp;또는&nbsp;본&nbsp;사이트의&nbsp;일부를&nbsp;포함하여&nbsp;프레이밍(frame)&nbsp;하거나&nbsp;프레이밍&nbsp;기술을&nbsp;활용할&nbsp;수&nbsp;있는&nbsp;권리</p>
<p>본&nbsp;사이트&nbsp;또는&nbsp;본&nbsp;컨텐츠의&nbsp;일부&nbsp;및/또는&nbsp;전부를&nbsp;재출판,&nbsp;재배포,&nbsp;전송,&nbsp;판매하거나,&nbsp;본&nbsp;사이트&nbsp;또는&nbsp;본&nbsp;컨텐츠의&nbsp;일부&nbsp;및/또는&nbsp;전부에&nbsp;사용권을&nbsp;허용하거나,&nbsp;동&nbsp;사이트&nbsp;등을&nbsp;다운로드할&nbsp;수&nbsp;있는&nbsp;권리(캐싱이나&nbsp;본&nbsp;사이트를&nbsp;조회하기&nbsp;위하여&nbsp;필요한&nbsp;경우를&nbsp;제외합니다.)</p>
<p>개인&nbsp;용도를&nbsp;제외한&nbsp;다른&nbsp;목적으로&nbsp;본&nbsp;사이트나&nbsp;본&nbsp;컨텐츠의&nbsp;일부&nbsp;및/또는&nbsp;전부를&nbsp;사용할&nbsp;수&nbsp;있는&nbsp;권리</p>
<p>본&nbsp;사이트나&nbsp;본&nbsp;컨텐츠의&nbsp;전부&nbsp;또는&nbsp;일부에&nbsp;기반한&nbsp;파생물을&nbsp;개작,&nbsp;역분석,&nbsp;또는&nbsp;생성할&nbsp;수&nbsp;있는&nbsp;권리</p>
<p>이용자&nbsp;또는&nbsp;다른&nbsp;상대방의&nbsp;이익을&nbsp;위하여&nbsp;계정&nbsp;정보를&nbsp;수집할&nbsp;수&nbsp;있는&nbsp;권리</p>
<p>메타&nbsp;태그(meta&nbsp;tags)&nbsp;또는&nbsp;본&nbsp;컨텐츠의&nbsp;일부&nbsp;및/또는&nbsp;전부를&nbsp;활용한&nbsp;&apos;숨겨진&nbsp;텍스트&apos;를&nbsp;사용할&nbsp;수&nbsp;있는&nbsp;권리</p>
<p>소프트웨어&nbsp;로봇,&nbsp;스파이더,&nbsp;크롤러&nbsp;또는&nbsp;이와&nbsp;유사한&nbsp;데이터&nbsp;수집&nbsp;및&nbsp;추출&nbsp;도구를&nbsp;사용할&nbsp;수&nbsp;있는&nbsp;권리나&nbsp;회사의&nbsp;기반시설에&nbsp;불합리한&nbsp;부담이나&nbsp;부하를&nbsp;줄&nbsp;수&nbsp;있는&nbsp;여타&nbsp;행동을&nbsp;할&nbsp;수&nbsp;있는&nbsp;권리</p>
<p>②&nbsp;회사는&nbsp;또한&nbsp;이용자에게&nbsp;개인적,&nbsp;비상업적&nbsp;용도에&nbsp;국한하여&nbsp;본&nbsp;사이트의&nbsp;홈페이지에&nbsp;하이퍼링크를&nbsp;설정할&nbsp;수&nbsp;있는&nbsp;제한적이고&nbsp;취소&nbsp;가능하며&nbsp;비독점적인&nbsp;이용권한을&nbsp;허용합니다.&nbsp;본&nbsp;사이트에&nbsp;링크된&nbsp;웹사이트는&nbsp;다음&nbsp;각&nbsp;호의&nbsp;사항을&nbsp;준수하여야&nbsp;합니다.</p>
<p>회사&nbsp;본&nbsp;컨텐츠의&nbsp;일부&nbsp;및/또는&nbsp;전부에&nbsp;링크될&nbsp;수는&nbsp;있지만&nbsp;본&nbsp;컨텐츠를&nbsp;복제할&nbsp;수&nbsp;없고,</p>
<p>회사가&nbsp;링크된&nbsp;사이트나&nbsp;동&nbsp;사이트의&nbsp;제품이나&nbsp;서비스를&nbsp;추천하는&nbsp;것을&nbsp;의미하지&nbsp;아니하며,</p>
<p>링크된&nbsp;사이트와&nbsp;회사와의&nbsp;관계를&nbsp;허위로&nbsp;표시할&nbsp;수&nbsp;없고,</p>
<p>혐오스럽고,&nbsp;외설적이며,&nbsp;불쾌하고,&nbsp;논쟁적이거나,&nbsp;불법적이거나,&nbsp;모든&nbsp;연령층에게&nbsp;부적합한&nbsp;것으로&nbsp;해석될&nbsp;수&nbsp;있는&nbsp;본&nbsp;컨텐츠를&nbsp;포함할&nbsp;수&nbsp;없으며,</p>
<p>회사나&nbsp;회사의&nbsp;제품&nbsp;또는&nbsp;서비스를&nbsp;폄하하거나&nbsp;허위로&nbsp;묘사하거나,&nbsp;또는&nbsp;불쾌하거나&nbsp;혐오스러운&nbsp;방식으로&nbsp;묘사할&nbsp;수&nbsp;없으며,&nbsp;회사를&nbsp;바람직하지&nbsp;않은&nbsp;제품,&nbsp;서비스,&nbsp;의견과&nbsp;연관시킬&nbsp;수&nbsp;없고,</p>
<p>홈페이지&nbsp;첫&nbsp;화면&nbsp;이외의&nbsp;본&nbsp;사이트&nbsp;웹&nbsp;페이지에&nbsp;링크할&nbsp;수&nbsp;없습니다.</p>
<p>③&nbsp;회사는&nbsp;재량&nbsp;하에&nbsp;이용자가&nbsp;본&nbsp;사이트에&nbsp;연결한&nbsp;모든&nbsp;링크를&nbsp;삭제할&nbsp;것을&nbsp;요청할&nbsp;수&nbsp;있으며,&nbsp;이용자는&nbsp;이와&nbsp;같은&nbsp;요청을&nbsp;받은&nbsp;즉시&nbsp;해당&nbsp;링크를&nbsp;삭제하고,&nbsp;링크설정을&nbsp;재개할&nbsp;수&nbsp;있는&nbsp;별도의&nbsp;명시적인&nbsp;서면&nbsp;승인을&nbsp;회사로부터&nbsp;득하지&nbsp;않는&nbsp;한&nbsp;일체의&nbsp;링크설정&nbsp;행위를&nbsp;중단하여야&nbsp;합니다.</p>
<p>④&nbsp;이용자가&nbsp;본&nbsp;사이트&nbsp;또는&nbsp;본&nbsp;컨텐츠의&nbsp;일부&nbsp;및/또는&nbsp;전부를&nbsp;승인&nbsp;받지&nbsp;않고&nbsp;상업적&nbsp;목적으로&nbsp;사용할&nbsp;경우,&nbsp;규정된&nbsp;제한적&nbsp;이용권한은&nbsp;관련&nbsp;법률이나&nbsp;본&nbsp;약관에&nbsp;규정된&nbsp;여타&nbsp;구제책에&nbsp;영향을&nbsp;미치지&nbsp;아니한&nbsp;채&nbsp;자동적으로&nbsp;해지됩니다.</p>
<p>&nbsp;</p>
<p>제16조&nbsp;이용자의&nbsp;의무&nbsp;및&nbsp;책임</p>
<p>이용자는&nbsp;본&nbsp;사이트에&nbsp;접속하거나&nbsp;본&nbsp;사이트를&nbsp;이용하는&nbsp;과정에서&nbsp;본&nbsp;약관과&nbsp;본&nbsp;사이트에&nbsp;게재된&nbsp;접속&nbsp;및&nbsp;사용과&nbsp;관련된&nbsp;특별한&nbsp;경고나&nbsp;지침을&nbsp;준수하여야&nbsp;합니다.&nbsp;이용자는&nbsp;항시&nbsp;법률,&nbsp;관습&nbsp;및&nbsp;신의에&nbsp;따라&nbsp;행동해야&nbsp;합니다.&nbsp;이용자는&nbsp;본&nbsp;사이트&nbsp;또는&nbsp;본&nbsp;사이트에&nbsp;나타날&nbsp;수&nbsp;있는&nbsp;모든&nbsp;컨텐츠&nbsp;또는&nbsp;서비스를&nbsp;변경할&nbsp;수&nbsp;없으며,&nbsp;어떠한&nbsp;방식으로도&nbsp;본&nbsp;사이트의&nbsp;완결성이나&nbsp;본&nbsp;사이트의&nbsp;운영을&nbsp;훼손,&nbsp;방해할&nbsp;수&nbsp;없습니다.&nbsp;본&nbsp;약관의&nbsp;여타&nbsp;조항의&nbsp;일반성을&nbsp;제한하지&nbsp;않는&nbsp;범위&nbsp;내에서&nbsp;본&nbsp;약관에&nbsp;규정된&nbsp;의무사항을&nbsp;고의&nbsp;또는&nbsp;과실로&nbsp;이행하지&nbsp;못할&nbsp;경우,&nbsp;이용자는&nbsp;회사,&nbsp;파트너,&nbsp;라이센서에게&nbsp;발생할&nbsp;수&nbsp;있는&nbsp;모든&nbsp;손실과&nbsp;손해에&nbsp;대한&nbsp;책임을&nbsp;부담할&nbsp;것입니다.</p>
<p>이용자는&nbsp;다음&nbsp;각&nbsp;호의&nbsp;행위를&nbsp;하여서는&nbsp;안됩니다.</p>
<p>①&nbsp;회원&nbsp;가입을&nbsp;포함한&nbsp;각종&nbsp;신청&nbsp;또는&nbsp;변경&nbsp;시&nbsp;허위&nbsp;내용을&nbsp;등록하는&nbsp;행위</p>
<p>②&nbsp;타인의&nbsp;정보&nbsp;도용</p>
<p>③&nbsp;Mood&nbsp;Ritual&nbsp;몰이&nbsp;게시한&nbsp;정보의&nbsp;변경</p>
<p>④&nbsp;Mood&nbsp;Ritual&nbsp;몰이&nbsp;정한&nbsp;정보&nbsp;이외의&nbsp;정보&nbsp;(컴퓨터&nbsp;프로그램&nbsp;등)&nbsp;등의&nbsp;송신&nbsp;또는&nbsp;게시</p>
<p>⑤&nbsp;Mood&nbsp;Ritual&nbsp;몰&nbsp;및&nbsp;기타&nbsp;제&nbsp;3자의&nbsp;저작권&nbsp;등&nbsp;지적&nbsp;재산권에&nbsp;대한&nbsp;침해</p>
<p>⑥&nbsp;Mood&nbsp;Ritual&nbsp;몰&nbsp;및&nbsp;기타&nbsp;제&nbsp;3자의&nbsp;명예를&nbsp;손상시키거나&nbsp;업무를&nbsp;방해하는&nbsp;행위</p>
<p>⑦&nbsp;외설&nbsp;또는&nbsp;폭력적인&nbsp;메시지,&nbsp;화상,&nbsp;음성,&nbsp;기타&nbsp;공서&nbsp;양속에&nbsp;반하는&nbsp;정보를&nbsp;서비스에&nbsp;공개&nbsp;또는&nbsp;게시하는&nbsp;행위</p>
<p>&nbsp;</p>
<p>제17조&nbsp;Mood&nbsp;Ritual&nbsp;몰과&nbsp;피연결&nbsp;서비스&nbsp;간의&nbsp;관계</p>
<p>제&nbsp;3자가&nbsp;제공하는&nbsp;사이트나&nbsp;컨텐츠가&nbsp;서비스를&nbsp;통해&nbsp;안내&nbsp;되었거나&nbsp;서비스와&nbsp;Hyperlink&nbsp;방식&nbsp;등으로&nbsp;연결된&nbsp;경우,&nbsp;이러한&nbsp;사이트나&nbsp;컨텐츠를&nbsp;&quot;피연결&nbsp;서비스&quot;라&nbsp;합니다.&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;이용자가&nbsp;피연결&nbsp;서비스가&nbsp;독자적으로&nbsp;제공하는&nbsp;사이트나&nbsp;컨텐츠&nbsp;및&nbsp;각종&nbsp;재화와&nbsp;용역을&nbsp;이용하는데&nbsp;있어,&nbsp;그&nbsp;이용과&nbsp;그로&nbsp;인해&nbsp;발생하는&nbsp;사항에&nbsp;대한&nbsp;책임을&nbsp;지지&nbsp;않습니다.</p>
<p>&nbsp;</p>
<p>제18조&nbsp;이용자&nbsp;계정</p>
<p>이용자가&nbsp;만&nbsp;14세&nbsp;이상일&nbsp;경우,&nbsp;본&nbsp;사이트에&nbsp;등록할&nbsp;수&nbsp;있습니다.&nbsp;이용자가&nbsp;만&nbsp;14세&nbsp;이상이고&nbsp;실제&nbsp;본&nbsp;사이트에&nbsp;등록할&nbsp;경우,&nbsp;이용자의&nbsp;계정용&nbsp;이메일&nbsp;주소,&nbsp;이용자&nbsp;ID&nbsp;및&nbsp;패스워드를&nbsp;갖게&nbsp;됩니다.&nbsp;이용자는&nbsp;본인&nbsp;계정,&nbsp;이용자ID,&nbsp;패스워드의&nbsp;보안을&nbsp;유지하고,&nbsp;타인이&nbsp;이용자의&nbsp;컴퓨터에&nbsp;접속하는&nbsp;것을&nbsp;제한하여야&nbsp;할&nbsp;책임이&nbsp;있습니다.&nbsp;이용자는&nbsp;전술한&nbsp;정보의&nbsp;유효성,&nbsp;완전성,&nbsp;정확성&nbsp;및&nbsp;진실성을&nbsp;유지하여야&nbsp;할&nbsp;책임이&nbsp;있습니다.&nbsp;이용자는&nbsp;이용자의&nbsp;계정,&nbsp;이용자ID&nbsp;및/또는&nbsp;패스워드&nbsp;하에&nbsp;발생하는&nbsp;모든&nbsp;행위에&nbsp;대하여&nbsp;책임을&nbsp;지는&nbsp;것에&nbsp;동의합니다.</p>
<p>이용자는&nbsp;현재&nbsp;유효하고,&nbsp;완전하고,&nbsp;정확하며&nbsp;진실한&nbsp;정보만을&nbsp;제공할&nbsp;것에&nbsp;동의합니다.&nbsp;이용자가&nbsp;타인을&nbsp;대신하여&nbsp;본&nbsp;사이트에&nbsp;접속하여&nbsp;사용할&nbsp;경우,&nbsp;이용자는&nbsp;그가&nbsp;본인의&nbsp;자격으로&nbsp;본&nbsp;약관에서&nbsp;규정된&nbsp;모든&nbsp;조건에&nbsp;구속되게&nbsp;할&nbsp;권한을&nbsp;보유하고&nbsp;있음을&nbsp;진술하고,&nbsp;그러한&nbsp;권한을&nbsp;부여&nbsp;받지&nbsp;못하는&nbsp;한,&nbsp;이용자는&nbsp;본&nbsp;약관의&nbsp;적용을&nbsp;받고&nbsp;그와&nbsp;같은&nbsp;본&nbsp;사이트에&nbsp;대한&nbsp;접속이나&nbsp;사용으로부터&nbsp;발생할&nbsp;수&nbsp;있는&nbsp;본&nbsp;사이트&nbsp;또는&nbsp;본&nbsp;컨텐츠의&nbsp;오용에&nbsp;의한&nbsp;손해에&nbsp;대하여&nbsp;책임을&nbsp;부담함을&nbsp;승낙합니다.</p>
<p>본&nbsp;약관에&nbsp;위반하는&nbsp;경우&nbsp;회사는&nbsp;사전통지&nbsp;없이&nbsp;서비스의&nbsp;제공을&nbsp;거부하거나&nbsp;또는&nbsp;제공을&nbsp;거부하고&nbsp;계정을&nbsp;해지할&nbsp;권리를&nbsp;보유합니다.</p>
<p>&nbsp;</p>
<p>제19조&nbsp;제3자&nbsp;링크</p>
<p>회사는&nbsp;본&nbsp;사이트로부터&nbsp;또는&nbsp;본&nbsp;사이트에&nbsp;링크된&nbsp;일체의&nbsp;오프웹사이트&nbsp;페이지들(off-website&nbsp;pages)&nbsp;또는&nbsp;여타&nbsp;웹사이트의&nbsp;컨텐츠에&nbsp;대해&nbsp;책임지지&nbsp;않습니다.&nbsp;본&nbsp;사이트에&nbsp;나타나는&nbsp;링크는&nbsp;사용&nbsp;상의&nbsp;편의를&nbsp;위한&nbsp;것이며,&nbsp;회사나&nbsp;파트너가&nbsp;링크&nbsp;상의&nbsp;컨텐츠,&nbsp;제품,&nbsp;서비스&nbsp;또는&nbsp;공급업체를&nbsp;추천하는&nbsp;것은&nbsp;아닙니다.</p>
<p>본&nbsp;사이트로부터&nbsp;또는&nbsp;본&nbsp;사이트에&nbsp;링크된&nbsp;일체의&nbsp;오프웹사이트&nbsp;페이지나&nbsp;여타&nbsp;웹사이트에&nbsp;링크를&nbsp;설정함으로&nbsp;인한&nbsp;위험은&nbsp;이용자가&nbsp;부담합니다.&nbsp;회사는&nbsp;링크된&nbsp;사이트를&nbsp;심사&nbsp;또는&nbsp;평가할&nbsp;의무를&nbsp;부담하지&nbsp;않고,&nbsp;본&nbsp;사이트로부터&nbsp;또는&nbsp;본&nbsp;사이트에&nbsp;링크된&nbsp;일체의&nbsp;오프웹사이트나&nbsp;여타&nbsp;웹사이트의&nbsp;컨텐츠를&nbsp;보증하지&nbsp;않으며,&nbsp;그러한&nbsp;페이지나&nbsp;웹사이트의&nbsp;개인정보취급방침&nbsp;및&nbsp;약관을&nbsp;포함하여&nbsp;동&nbsp;페이지&nbsp;및&nbsp;웹사이트의&nbsp;조치,&nbsp;컨텐츠,&nbsp;제품&nbsp;또는&nbsp;서비스에&nbsp;대해&nbsp;아무런&nbsp;책임이나&nbsp;의무를&nbsp;부담하지&nbsp;않습니다.&nbsp;이용자는&nbsp;방문하는&nbsp;모든&nbsp;오프&nbsp;웹사이트&nbsp;페이지&nbsp;및&nbsp;여타&nbsp;웹사이트의&nbsp;약관&nbsp;및&nbsp;개인정보취급방침을&nbsp;주의&nbsp;깊게&nbsp;검토하여야&nbsp;합니다.</p>
<p>&nbsp;</p>
<p>제20조&nbsp;특별&nbsp;게시물,&nbsp;기능&nbsp;및&nbsp;이벤트</p>
<p>본&nbsp;사이트는&nbsp;특별&nbsp;게시물,&nbsp;기능&nbsp;또는&nbsp;이벤트(컨테스트,&nbsp;경품행사,&nbsp;기타&nbsp;이벤트&nbsp;등)를&nbsp;제공할&nbsp;수&nbsp;있고,&nbsp;그&nbsp;게시물&nbsp;등은&nbsp;본&nbsp;약관에&nbsp;추가되거나&nbsp;또는&nbsp;본&nbsp;약관을&nbsp;대신하는&nbsp;이용&nbsp;조건,&nbsp;규칙&nbsp;및/또는&nbsp;정책의&nbsp;적용을&nbsp;받을&nbsp;수&nbsp;있으며,&nbsp;회사나&nbsp;제3자에&nbsp;의하여&nbsp;제공될&nbsp;수&nbsp;있습니다.&nbsp;이&nbsp;경우,&nbsp;회사는&nbsp;이용자에게&nbsp;그러한&nbsp;사실을&nbsp;통지하며,&nbsp;이용자가&nbsp;위와&nbsp;같은&nbsp;이벤트&nbsp;등을&nbsp;이용하고자&nbsp;할&nbsp;경우&nbsp;추가적인&nbsp;또는&nbsp;별도의&nbsp;이용&nbsp;조건,&nbsp;규칙&nbsp;및/또는&nbsp;정책에&nbsp;의한&nbsp;적용을&nbsp;받을&nbsp;수&nbsp;있음에&nbsp;동의합니다.</p>
<p>&nbsp;</p>
<p>제21조&nbsp;저작권의&nbsp;귀속&nbsp;및&nbsp;이용제한</p>
<p>①&nbsp;Mood&nbsp;Ritual&nbsp;몰이&nbsp;작성한&nbsp;저작물에&nbsp;대한&nbsp;저작권&nbsp;기타&nbsp;지적재산권은&nbsp;Mood&nbsp;Ritual&nbsp;몰에&nbsp;귀속합니다.</p>
<p>②&nbsp;이용자는&nbsp;Mood&nbsp;Ritual&nbsp;몰을&nbsp;이용함으로써&nbsp;얻은&nbsp;정보&nbsp;중&nbsp;Mood&nbsp;Ritual&nbsp;몰에&nbsp;지적&nbsp;재산권이&nbsp;귀속된&nbsp;정보를&nbsp;Mood&nbsp;Ritual&nbsp;몰의&nbsp;사전&nbsp;승낙&nbsp;없이&nbsp;복제,&nbsp;전송,&nbsp;출판,&nbsp;배포,&nbsp;방송&nbsp;기타&nbsp;방법에&nbsp;의하여&nbsp;영리목적으로&nbsp;이용하거나&nbsp;제&nbsp;3자에게&nbsp;이용하게&nbsp;하여서는&nbsp;안됩니다.</p>
<p>③&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;이용자가&nbsp;올린&nbsp;컨텐츠의&nbsp;전체&nbsp;또는&nbsp;일부분을&nbsp;검열할&nbsp;권리가&nbsp;있으며,&nbsp;컨텐츠를&nbsp;편집,&nbsp;포스트&nbsp;거절&nbsp;또는&nbsp;삭제할&nbsp;권한을&nbsp;가지고&nbsp;있습니다.&nbsp;또한&nbsp;회사가&nbsp;영위하는&nbsp;사업과&nbsp;관련하여&nbsp;이용자&nbsp;창작&nbsp;컨텐츠를&nbsp;공개하거나&nbsp;컨텐츠를&nbsp;Mood&nbsp;Ritual&nbsp;몰&nbsp;외부로&nbsp;전송하는&nbsp;등의&nbsp;방법으로&nbsp;제3자에게&nbsp;컨텐츠를&nbsp;제공할&nbsp;수&nbsp;있습니다.</p>
<p>④&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;이용자가&nbsp;올린&nbsp;컨텐츠에&nbsp;포함된&nbsp;댓글,&nbsp;정보,&nbsp;디자인,&nbsp;아이디어&nbsp;및&nbsp;웹사이트에&nbsp;접속하고&nbsp;있는&nbsp;동안&nbsp;만든&nbsp;모든&nbsp;컨텐츠,&nbsp;Mood&nbsp;Ritual에&nbsp;보낸&nbsp;의견에&nbsp;포함되어&nbsp;있는&nbsp;정보를&nbsp;이용할&nbsp;수&nbsp;있습니다.&nbsp;이를&nbsp;바탕으로&nbsp;제품&nbsp;개발,&nbsp;제조,&nbsp;마케팅,&nbsp;웹사이트,&nbsp;서비스&nbsp;또는&nbsp;기타&nbsp;제품이나&nbsp;서비스의&nbsp;창작,&nbsp;변경&nbsp;개발&nbsp;등&nbsp;회사가&nbsp;영위하는&nbsp;사업과&nbsp;관련하여&nbsp;사전의&nbsp;공지,&nbsp;보상이나&nbsp;연락&nbsp;없이&nbsp;사용할&nbsp;수&nbsp;있습니다.&nbsp;다만,&nbsp;관련법령상&nbsp;이용자가&nbsp;올린&nbsp;컨텐츠를&nbsp;수집,&nbsp;사용,&nbsp;제공,&nbsp;처리하기&nbsp;위하여&nbsp;이용자의&nbsp;동의가&nbsp;필요한&nbsp;경우&nbsp;회사는&nbsp;관련법령에&nbsp;따라&nbsp;해당&nbsp;동의를&nbsp;받을&nbsp;것입니다.</p>
<p>&nbsp;</p>
<p>제22조.&nbsp;광고게재&nbsp;등</p>
<p>Mood&nbsp;Ritual&nbsp;몰은&nbsp;이용자에게&nbsp;최상의&nbsp;서비스를&nbsp;원활하게&nbsp;제공하기&nbsp;위한&nbsp;재정기반을&nbsp;마련하기&nbsp;위하여&nbsp;상업용&nbsp;광고를&nbsp;화면에&nbsp;게재하거나&nbsp;이메일&nbsp;또는&nbsp;DM(서신),&nbsp;SMS,&nbsp;전화,&nbsp;등을&nbsp;이용하여&nbsp;광고성&nbsp;정보&nbsp;수신에&nbsp;동의한&nbsp;개별&nbsp;이용자에게&nbsp;보낼&nbsp;수&nbsp;있습니다.&nbsp;단,&nbsp;회사로&nbsp;서신,&nbsp;유선상&nbsp;수신거절의&nbsp;의사를&nbsp;명백히&nbsp;표시한&nbsp;이용자에&nbsp;대해서는&nbsp;더&nbsp;이상&nbsp;이메일&nbsp;또는&nbsp;DM(서신),&nbsp;SMS,&nbsp;전화&nbsp;등을&nbsp;하지&nbsp;않습니다.</p>
<p>Mood&nbsp;Ritual&nbsp;몰은&nbsp;본&nbsp;서비스를&nbsp;통한&nbsp;광고주의&nbsp;판촉활동에&nbsp;회원이&nbsp;직접&nbsp;참여함으로써&nbsp;발생하는&nbsp;손해에&nbsp;대하여는&nbsp;아무런&nbsp;책임을&nbsp;부담하지&nbsp;않습니다.</p>
<p>&nbsp;</p>
<p>제23조&nbsp;제안</p>
<p>①&nbsp;회사가&nbsp;요청하지&nbsp;않은&nbsp;제안&nbsp;및&nbsp;아이디어는&nbsp;거절하는&nbsp;것이&nbsp;회사의&nbsp;방침입니다.&nbsp;요청하지&nbsp;않은&nbsp;제안&nbsp;및&nbsp;아이디어에&nbsp;대한&nbsp;회사의&nbsp;정책에도&nbsp;불구하고,&nbsp;질의,&nbsp;피드백,&nbsp;제안,&nbsp;아이디어&nbsp;또는&nbsp;이용자가&nbsp;회사에&nbsp;제공한&nbsp;정보&nbsp;(통칭하여,&nbsp;&apos;제안&apos;)는&nbsp;독점성이나&nbsp;기밀성이&nbsp;없는&nbsp;것으로&nbsp;취급될&nbsp;것입니다.</p>
<p>②&nbsp;회사의&nbsp;개인정보취급방침의&nbsp;조건에&nbsp;따라,&nbsp;이용자가&nbsp;제공한&nbsp;정보를&nbsp;전송하거나&nbsp;게시함으로써,&nbsp;이용자는&nbsp;동&nbsp;제안의&nbsp;전부&nbsp;또는&nbsp;일부를&nbsp;복제하거나,&nbsp;그로부터&nbsp;파생물을&nbsp;생성하거나,&nbsp;현재&nbsp;알려져&nbsp;있거나&nbsp;앞으로&nbsp;개발될&nbsp;모든&nbsp;형식,&nbsp;매체,&nbsp;기술의&nbsp;형태로&nbsp;단독으로&nbsp;또는&nbsp;기타&nbsp;작업물의&nbsp;일부로서&nbsp;그&nbsp;제안을&nbsp;배포하고&nbsp;전시하거나,&nbsp;회사의&nbsp;제품&nbsp;또는&nbsp;서비스와&nbsp;관련하여&nbsp;또는&nbsp;그에&nbsp;포함하여&nbsp;제안을&nbsp;사용하는&nbsp;것을&nbsp;포함하여&nbsp;회사가&nbsp;적절하다고&nbsp;판단한&nbsp;어떠한&nbsp;방식으로&nbsp;제안을&nbsp;복제,&nbsp;사용,&nbsp;재생,&nbsp;변경,&nbsp;개조,&nbsp;번역,&nbsp;출판,&nbsp;사용권&nbsp;허여,&nbsp;배포,&nbsp;판매&nbsp;또는&nbsp;양도할&nbsp;권리를&nbsp;부여합니다.</p>
<p>③&nbsp;또한&nbsp;이용자는&nbsp;이용자의&nbsp;제안이&nbsp;반환되지&nbsp;않으며,&nbsp;이용자가&nbsp;제공한&nbsp;정보&nbsp;및&nbsp;동&nbsp;정보에&nbsp;포함된&nbsp;아이디어,&nbsp;컨셉,&nbsp;노하우&nbsp;일체에&nbsp;대하여&nbsp;회사가&nbsp;금전&nbsp;또는&nbsp;다른&nbsp;형태의&nbsp;대가의&nbsp;지급&nbsp;없이,&nbsp;제품의&nbsp;개발,&nbsp;제조,&nbsp;유통&nbsp;및&nbsp;마케팅을&nbsp;포함하나&nbsp;그에&nbsp;국한되지&nbsp;않는&nbsp;모든&nbsp;목적으로&nbsp;사용할&nbsp;수&nbsp;있다는&nbsp;것을&nbsp;인정합니다.</p>
<p>④&nbsp;이용자가&nbsp;제안을&nbsp;한&nbsp;경우,&nbsp;이용자는&nbsp;자신의&nbsp;제안에&nbsp;대해&nbsp;권리를&nbsp;소유하거나&nbsp;달리&nbsp;관리하고&nbsp;있다는&nbsp;점을&nbsp;진술&nbsp;및&nbsp;보증합니다.&nbsp;이용자는&nbsp;또한&nbsp;그러한&nbsp;제안이&nbsp;소프트웨어&nbsp;바이러스,&nbsp;구매요청,&nbsp;연쇄메일,&nbsp;대량메일,&nbsp;또는&nbsp;여타&nbsp;형태의&nbsp;&apos;스팸&apos;에&nbsp;해당하거나&nbsp;소프트웨어&nbsp;바이러스&nbsp;등을&nbsp;포함하지&nbsp;않는다는&nbsp;것을&nbsp;진술&nbsp;및&nbsp;보증합니다.&nbsp;이용자는&nbsp;허위&nbsp;이메일&nbsp;주소를&nbsp;사용하거나,&nbsp;허위로&nbsp;타인인&nbsp;체&nbsp;하거나,&nbsp;달리&nbsp;제안의&nbsp;출처에&nbsp;대하여&nbsp;회사를&nbsp;기만할&nbsp;수&nbsp;없습니다.&nbsp;이용자는&nbsp;제안에&nbsp;관한&nbsp;권리의&nbsp;소유권&nbsp;주장이나&nbsp;동&nbsp;정보로부터&nbsp;발생한&nbsp;손해와&nbsp;관련하여,&nbsp;또는&nbsp;그로부터&nbsp;발생하는&nbsp;모든&nbsp;청구에&nbsp;대하여&nbsp;회사를&nbsp;면책함에&nbsp;동의합니다.</p>
<p>제24조&nbsp;이용자&nbsp;컨텐츠</p>
<p>①&nbsp;이용자가&nbsp;자료,&nbsp;텍스트,&nbsp;소프트웨어,&nbsp;음악,&nbsp;음향자료,&nbsp;사진,&nbsp;그래픽,&nbsp;이미지,&nbsp;비디오,&nbsp;메시지,&nbsp;기타&nbsp;자료&nbsp;등&nbsp;(&apos;이용자&nbsp;컨텐츠&apos;)을&nbsp;본&nbsp;사이트에서&nbsp;전송,&nbsp;업로드,&nbsp;게시,&nbsp;이메일&nbsp;전송&nbsp;또는&nbsp;달리&nbsp;이용가능하도록&nbsp;할&nbsp;경우,&nbsp;이용자는&nbsp;그와&nbsp;같은&nbsp;이용자&nbsp;컨텐츠에&nbsp;대해&nbsp;전적으로&nbsp;책임을&nbsp;부담합니다.&nbsp;즉,&nbsp;해당&nbsp;이용자가&nbsp;사이트에&nbsp;게시하는&nbsp;모든&nbsp;이용자&nbsp;컨텐츠에&nbsp;대하여&nbsp;회사가&nbsp;아니라&nbsp;해당&nbsp;이용자가&nbsp;전적으로&nbsp;책임을&nbsp;진다는&nbsp;것을&nbsp;의미합니다.</p>
<p>②&nbsp;이용자는&nbsp;다음&nbsp;각&nbsp;호의&nbsp;사항을&nbsp;준수합니다.</p>
<p>불법적이거나,&nbsp;해롭거나,&nbsp;위협적이거나,&nbsp;폭력적이거나,&nbsp;또는&nbsp;타인의&nbsp;심기를&nbsp;불편하게&nbsp;하거나,&nbsp;명예훼손적이거나,&nbsp;천박하거나,&nbsp;외설적이거나,&nbsp;비방적이거나,&nbsp;타인의&nbsp;사생활을&nbsp;침해하거나,&nbsp;혐오스럽거나,&nbsp;아니면&nbsp;인종적으로&nbsp;또는&nbsp;윤리적으로&nbsp;반감을&nbsp;불러일으키는&nbsp;이용자&nbsp;컨텐츠를&nbsp;본&nbsp;사이트에서&nbsp;전송,&nbsp;업로드,&nbsp;게시,&nbsp;이메일&nbsp;전송&nbsp;또는&nbsp;달리&nbsp;공개할&nbsp;수&nbsp;없고,&nbsp;다른&nbsp;사람들이&nbsp;이러한&nbsp;컨텐츠를&nbsp;본&nbsp;사이트에서&nbsp;전송,&nbsp;업로드,&nbsp;게시,&nbsp;이메일&nbsp;전송&nbsp;또는&nbsp;달리&nbsp;공개하도록&nbsp;돕거나&nbsp;조장할&nbsp;수&nbsp;없습니다.</p>
<p>이용자는&nbsp;법률이나&nbsp;계약&nbsp;또는&nbsp;신뢰&nbsp;관계상&nbsp;전술한&nbsp;성격의&nbsp;이용자&nbsp;컨텐츠를&nbsp;이용가능하게&nbsp;할&nbsp;권리를&nbsp;가지지&nbsp;않는다는&nbsp;점에&nbsp;동의합니다.</p>
<p>이용자는&nbsp;회사와&nbsp;이용자&nbsp;중&nbsp;일방의&nbsp;특허권,&nbsp;상표권,&nbsp;영업비밀,&nbsp;저작권&nbsp;또는&nbsp;기타&nbsp;재산권을&nbsp;침해하는&nbsp;이용자&nbsp;컨텐츠를&nbsp;본&nbsp;사이트에서&nbsp;전송,&nbsp;업로드,&nbsp;게시,&nbsp;이메일&nbsp;전송&nbsp;또는&nbsp;달리&nbsp;이용가능하게&nbsp;할&nbsp;수&nbsp;없다는&nbsp;점에&nbsp;대하여&nbsp;동의합니다.</p>
<p>이용자는&nbsp;연쇄메일,&nbsp;대량메일&nbsp;또는&nbsp;여타&nbsp;형태의&nbsp;&apos;스팸&apos;을&nbsp;포함하여&nbsp;소프트웨어&nbsp;바이러스,&nbsp;원치&nbsp;않는&nbsp;광고물이나&nbsp;승인받지&nbsp;않은&nbsp;광고물,&nbsp;구매요청이나&nbsp;홍보자료&nbsp;등을&nbsp;전송,&nbsp;업로드,&nbsp;게시,&nbsp;이메일&nbsp;전송&nbsp;또는&nbsp;달리&nbsp;이용가능하게&nbsp;할&nbsp;수&nbsp;없다는&nbsp;점에&nbsp;대하여&nbsp;동의합니다.</p>
<p>이용자는&nbsp;다른&nbsp;사람을&nbsp;허위로&nbsp;대리하거나,&nbsp;특정인이나&nbsp;특정&nbsp;단체와의&nbsp;관계를&nbsp;허위로&nbsp;또는&nbsp;부정확하게&nbsp;진술하지&nbsp;않습니다.</p>
<p>이용자는&nbsp;제3자를&nbsp;&apos;스토킹&apos;하거나&nbsp;또는&nbsp;달리&nbsp;괴롭히거나,&nbsp;모함하거나,&nbsp;해를&nbsp;끼치지&nbsp;않습니다.</p>
<p>이용자는&nbsp;이용자&nbsp;컨텐츠의&nbsp;출처를&nbsp;가장하기&nbsp;위하여&nbsp;헤더(header)를&nbsp;위조하거나&nbsp;식별표시&nbsp;등을&nbsp;달리&nbsp;조작하지&nbsp;않습니다.</p>
<p>이용자는&nbsp;고의성의&nbsp;유무를&nbsp;불문하고&nbsp;관련&nbsp;지역,&nbsp;국가의&nbsp;법률&nbsp;또는&nbsp;국제법을&nbsp;위반하지&nbsp;않습니다.</p>
<p>이용자는&nbsp;다른&nbsp;이용자에&nbsp;대하여&nbsp;개인&nbsp;식별이&nbsp;가능한&nbsp;데이터를&nbsp;수집하거나&nbsp;저장하지&nbsp;아니한다는&nbsp;점에&nbsp;대하여&nbsp;동의합니다.</p>
<p>③&nbsp;회사는&nbsp;이용자가&nbsp;생성하여&nbsp;사이트에&nbsp;전송&nbsp;또는&nbsp;게시한&nbsp;컨텐츠를&nbsp;보증하거나&nbsp;제어하지&nbsp;않습니다.&nbsp;따라서&nbsp;회사는&nbsp;이용자&nbsp;컨텐츠의&nbsp;정확성,&nbsp;진실성&nbsp;또는&nbsp;품질을&nbsp;보장하지&nbsp;않습니다.</p>
<p>④&nbsp;이용자는&nbsp;본&nbsp;사이트를&nbsp;사용함으로써&nbsp;이용자에게&nbsp;불쾌하고&nbsp;음란하며&nbsp;반감을&nbsp;일으킬&nbsp;수&nbsp;있는&nbsp;이용자&nbsp;컨텐츠에&nbsp;노출될&nbsp;수&nbsp;있다는&nbsp;점을&nbsp;양지합니다.&nbsp;어떠한&nbsp;상황에서도,&nbsp;회사는&nbsp;이용자&nbsp;컨텐츠상&nbsp;오류나&nbsp;누락을&nbsp;포함한&nbsp;일체의&nbsp;이용자&nbsp;컨텐츠에&nbsp;대해서,&nbsp;또는&nbsp;본&nbsp;사이트를&nbsp;통하여&nbsp;전송,&nbsp;업로드,&nbsp;게시,&nbsp;이메일&nbsp;전송&nbsp;또는&nbsp;달리&nbsp;공개된&nbsp;이용자&nbsp;컨텐츠를&nbsp;사용함으로써&nbsp;이용자에게&nbsp;발생한&nbsp;모든&nbsp;성격의&nbsp;손실이나&nbsp;손해에&nbsp;대해서&nbsp;일체의&nbsp;책임을&nbsp;지지&nbsp;않습니다.</p>
<p>⑤&nbsp;이용자는&nbsp;회사가&nbsp;회사의&nbsp;재량으로&nbsp;이용자&nbsp;컨텐츠의&nbsp;게시를&nbsp;거부하거나&nbsp;동&nbsp;컨텐츠를&nbsp;제거할&nbsp;수&nbsp;있는&nbsp;권리(의무는&nbsp;아님)를&nbsp;가짐을&nbsp;인정합니다.&nbsp;전술사항이나&nbsp;본&nbsp;약관의&nbsp;여타&nbsp;조항의&nbsp;일반성을&nbsp;제한하지&nbsp;않고,&nbsp;회사는&nbsp;본&nbsp;약관을&nbsp;위반하거나&nbsp;달리&nbsp;반감을&nbsp;일으키는&nbsp;이용자&nbsp;컨텐츠에&nbsp;대해서는&nbsp;이를&nbsp;제거할&nbsp;수&nbsp;있는&nbsp;권리를&nbsp;지니며,&nbsp;본&nbsp;약관을&nbsp;위반하거나&nbsp;타인의&nbsp;권리를&nbsp;침해하는&nbsp;이용자에&nbsp;대해서는&nbsp;통지&nbsp;후&nbsp;서비스의&nbsp;제공을&nbsp;거부하거나&nbsp;또는&nbsp;서비스의&nbsp;제공을&nbsp;거부하고&nbsp;이용자의&nbsp;계정을&nbsp;해지할&nbsp;권리를&nbsp;보유합니다.</p>
<p>&nbsp;</p>
<p>제25조&nbsp;저작권&nbsp;관련&nbsp;불만</p>
<p>회사는&nbsp;타인의&nbsp;지적&nbsp;재산을&nbsp;존중합니다.&nbsp;한국의&nbsp;지적재산관련법에&nbsp;따라,&nbsp;저작권보호를&nbsp;받는&nbsp;컨텐츠가&nbsp;지적재산관련법&nbsp;위반에&nbsp;해당하는&nbsp;방식으로&nbsp;복제되었다고&nbsp;판단하는&nbsp;경우,&nbsp;이용자는&nbsp;완전하게&nbsp;작성된&nbsp;&apos;재생&nbsp;또는&nbsp;전송&nbsp;중단&nbsp;요청서&apos;&nbsp;및&nbsp;요청된&nbsp;정보와&nbsp;백업&nbsp;자료&nbsp;일체를&nbsp;회사의&nbsp;지정대리인에게&nbsp;이메일&nbsp;또는&nbsp;서면에&nbsp;의하여&nbsp;통지하여&nbsp;주십시오.</p>
<p>&nbsp;</p>
<p>제26조&nbsp;진술&nbsp;및&nbsp;보증(책임의&nbsp;제한)</p>
<p>본&nbsp;사이트는&nbsp;&apos;현&nbsp;상태&nbsp;그대로&apos;&nbsp;제시됩니다.&nbsp;회사는&nbsp;법적으로&nbsp;배제될&nbsp;수&nbsp;없는&nbsp;범위를&nbsp;제외하고는&nbsp;상품적합성,&nbsp;비침해&nbsp;또는&nbsp;특정&nbsp;목적에&nbsp;대한&nbsp;적합성에&nbsp;대한&nbsp;보증을&nbsp;포함하여&nbsp;(그러나&nbsp;이에&nbsp;한정되지&nbsp;아니합니다)&nbsp;본&nbsp;약관이나&nbsp;본&nbsp;사이트와&nbsp;관련하여&nbsp;어떠한&nbsp;종류의&nbsp;명시적&nbsp;또는&nbsp;묵시적인&nbsp;진술이나&nbsp;보증을&nbsp;하지&nbsp;아니합니다.</p>
<p>이용자는,&nbsp;관련&nbsp;법률이&nbsp;허용하는&nbsp;최대&nbsp;한도까지,&nbsp;(계약,&nbsp;불법행위(과실&nbsp;포함)&nbsp;및&nbsp;기타&nbsp;조건상),&nbsp;(1)&nbsp;사업장애,&nbsp;(2)&nbsp;접속&nbsp;지연&nbsp;또는&nbsp;본&nbsp;사이트에의&nbsp;접속&nbsp;장애,&nbsp;(3)&nbsp;데이터&nbsp;전송&nbsp;불가,&nbsp;전송오류,&nbsp;데이터&nbsp;훼손,&nbsp;파괴&nbsp;또는&nbsp;기타&nbsp;변형,&nbsp;(4)&nbsp;본&nbsp;사이트에서의&nbsp;오프웹사이트&nbsp;링크&nbsp;또는&nbsp;그&nbsp;링크를&nbsp;처리하는&nbsp;과정에서&nbsp;발생한&nbsp;모든&nbsp;종류의&nbsp;손실&nbsp;또는&nbsp;손해,&nbsp;(5)&nbsp;제3자&nbsp;웹사이트&nbsp;쪽으로&nbsp;또는&nbsp;그로부터&nbsp;하이퍼링크&nbsp;연결과정을&nbsp;포함하여&nbsp;이용자의&nbsp;본&nbsp;사이트&nbsp;사용과&nbsp;관련하여&nbsp;발생할&nbsp;수&nbsp;있는&nbsp;컴퓨터&nbsp;바이러스,&nbsp;시스템&nbsp;오류,&nbsp;또는&nbsp;오작동,&nbsp;(6)&nbsp;컨텐츠상&nbsp;부정확성이나&nbsp;누락&nbsp;또는&nbsp;(7)&nbsp;회사의&nbsp;합리적&nbsp;관리&nbsp;범위를&nbsp;넘어선&nbsp;사건&nbsp;일체에&nbsp;대하여,&nbsp;회사는&nbsp;어떠한&nbsp;상황에서도&nbsp;책임을&nbsp;부담하지&nbsp;아니함에&nbsp;대하여&nbsp;동의합니다.&nbsp;또한&nbsp;관련&nbsp;법률이&nbsp;허용하는&nbsp;최대&nbsp;한도까지,&nbsp;회사는&nbsp;손해배상의&nbsp;가능성에&nbsp;대해서&nbsp;사전에&nbsp;알고&nbsp;있었다고&nbsp;할지라도,&nbsp;계약&nbsp;(일실이익을&nbsp;포함합니다),&nbsp;불법행위&nbsp;(과실을&nbsp;포함합니다)&nbsp;또는&nbsp;기타&nbsp;행위의&nbsp;형태를&nbsp;불문하고,&nbsp;본&nbsp;사이트&nbsp;또는&nbsp;이용자의&nbsp;본&nbsp;사이트&nbsp;사용과&nbsp;관련한&nbsp;모든&nbsp;종류의&nbsp;간접적,&nbsp;특별한,&nbsp;징벌적,&nbsp;우발적&nbsp;또는&nbsp;후속적인&nbsp;손해에&nbsp;대하여&nbsp;책임을&nbsp;지지&nbsp;아니하며,&nbsp;어떠한&nbsp;경우에도&nbsp;회사의&nbsp;손해배상&nbsp;총액은&nbsp;한화&nbsp;금&nbsp;구만원(90,000원)을&nbsp;초과하지&nbsp;아니합니다.</p>
<p>&nbsp;</p>
<p>제27조&nbsp;면책</p>
<p>이용자는&nbsp;이용자의&nbsp;본&nbsp;사이트&nbsp;사용이나&nbsp;본&nbsp;약관&nbsp;위반으로부터&nbsp;기인한&nbsp;제3자의&nbsp;청구,&nbsp;소송&nbsp;또는&nbsp;권리주장으로&nbsp;인한&nbsp;일체의&nbsp;손실,&nbsp;손해,&nbsp;비용&nbsp;(합리적&nbsp;범위의&nbsp;변호사&nbsp;수임료를&nbsp;포함합니다)&nbsp;에&nbsp;대하여&nbsp;회사를&nbsp;보호하고&nbsp;면책함에&nbsp;동의합니다.&nbsp;이용자는&nbsp;또한&nbsp;이용자의&nbsp;소프트웨어&nbsp;로봇,&nbsp;스파이더,&nbsp;크롤러&nbsp;또는&nbsp;그와&nbsp;유사한&nbsp;데이터&nbsp;수집&nbsp;및&nbsp;추출&nbsp;도구를&nbsp;사용함으로써&nbsp;발생하거나,&nbsp;기타&nbsp;회사의&nbsp;기반시설에&nbsp;불합리한&nbsp;부담이나&nbsp;부하를&nbsp;주는&nbsp;어떠한&nbsp;행위를&nbsp;함으로&nbsp;인하여&nbsp;발생하는&nbsp;일체의&nbsp;손실,&nbsp;손해,&nbsp;비용&nbsp;(합리적&nbsp;범위의&nbsp;변호사&nbsp;수임료를&nbsp;포함합니다)&nbsp;에&nbsp;대해&nbsp;회사에게&nbsp;배상함에&nbsp;동의합니다.</p>
<p>&nbsp;</p>
<p>제28조&nbsp;분쟁</p>
<p>①&nbsp;본&nbsp;사이트에&nbsp;관한&nbsp;일체의&nbsp;분쟁과&nbsp;관련하여,&nbsp;본&nbsp;약관에&nbsp;의하여&nbsp;예상된&nbsp;이용자의&nbsp;권리와&nbsp;의무&nbsp;및&nbsp;모든&nbsp;행위는&nbsp;대한민국의&nbsp;법률에&nbsp;의하여&nbsp;규율될&nbsp;것입니다.&nbsp;Mood&nbsp;Ritual&nbsp;몰&rdquo;과&nbsp;&ldquo;이용자&rdquo;간에&nbsp;제기된&nbsp;&ldquo;서비스&rdquo;&nbsp;관련&nbsp;소송에는&nbsp;대한민국&nbsp;법을&nbsp;적용합니다.&nbsp;법에&nbsp;의하여&nbsp;허용되는&nbsp;최대&nbsp;한도&nbsp;내에서,&nbsp;회사와&nbsp;이용자&nbsp;간에&nbsp;발생한&nbsp;전자상거래&nbsp;분쟁에&nbsp;관한&nbsp;소송은&nbsp;제소&nbsp;당시의&nbsp;이용자의&nbsp;주소에&nbsp;의하고,&nbsp;주소가&nbsp;없을&nbsp;경우에는&nbsp;거소를&nbsp;관할하는&nbsp;지방법원의&nbsp;전속관할로&nbsp;합니다.&nbsp;다만,&nbsp;제소&nbsp;당시&nbsp;이용자의&nbsp;주소&nbsp;또는&nbsp;거소가&nbsp;분명하지&nbsp;않거나&nbsp;외국&nbsp;거주자의&nbsp;경우에는&nbsp;민사소송법상의&nbsp;관할법원에&nbsp;제기합니다.&nbsp;다만,&nbsp;이용자가&nbsp;동의할&nbsp;경우&nbsp;선택적으로&nbsp;중재&nbsp;신청이&nbsp;제기될&nbsp;수&nbsp;있습니다.</p>
<p>②&nbsp;이용자는&nbsp;상기&nbsp;관할&nbsp;및&nbsp;절차에&nbsp;따르되,&nbsp;다만&nbsp;예외적으로&nbsp;회사는&nbsp;이용자가&nbsp;회사의&nbsp;지적재산권이나&nbsp;회사&nbsp;계열사,&nbsp;파트너,&nbsp;라이센서의&nbsp;지적재산권을&nbsp;위반하였거나&nbsp;위반할&nbsp;우려가&nbsp;있는&nbsp;경우에는,&nbsp;관할법원에&nbsp;금지명령이나&nbsp;기타&nbsp;적절한&nbsp;구제조치를&nbsp;청구할&nbsp;수&nbsp;있습니다.</p>
<p>&nbsp;</p>
<p>제29조&nbsp;분쟁&nbsp;해결</p>
<p>①&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;이용자가&nbsp;서비스와&nbsp;관련하여&nbsp;제기하는&nbsp;정당한&nbsp;의견이나&nbsp;불만을&nbsp;반영하고&nbsp;그&nbsp;피해&nbsp;및&nbsp;보상&nbsp;처리를&nbsp;고객&nbsp;지원실을&nbsp;통해&nbsp;진행합니다.</p>
<p>②&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;서비스와&nbsp;관련하여&nbsp;이용자로부터&nbsp;제출되는&nbsp;불만사항&nbsp;및&nbsp;의견은&nbsp;우선적으로&nbsp;그&nbsp;사항을&nbsp;처리합니다.&nbsp;다만,&nbsp;신속한&nbsp;처리가&nbsp;곤란한&nbsp;경우에는&nbsp;이용자에게&nbsp;그&nbsp;사유와&nbsp;처리&nbsp;일정을&nbsp;즉시&nbsp;통보해&nbsp;줍니다.</p>
<p>③&nbsp;Mood&nbsp;Ritual&nbsp;몰과&nbsp;이용자간에&nbsp;발생한&nbsp;서비스&nbsp;이용과&nbsp;관련한&nbsp;이용자의&nbsp;피해&nbsp;구제&nbsp;신청이&nbsp;있는&nbsp;경우에는&nbsp;공정거래위원회&nbsp;또는&nbsp;시/도&nbsp;지사가&nbsp;의뢰하는&nbsp;분쟁&nbsp;조정&nbsp;기관의&nbsp;조정에&nbsp;따를&nbsp;수&nbsp;있습니다.</p>
<p>&nbsp;</p>
<p>제30조&nbsp;이용자에&nbsp;대한&nbsp;통지&nbsp;방법</p>
<p>①&nbsp;Mood&nbsp;Ritual&nbsp;몰이&nbsp;특정&nbsp;이용자&nbsp;또는&nbsp;회원에&nbsp;대한&nbsp;통지를&nbsp;하는&nbsp;경우&nbsp;회원이&nbsp;Mood&nbsp;Ritual&nbsp;몰에&nbsp;미리&nbsp;약정하여&nbsp;지정한&nbsp;전자우편&nbsp;주소&nbsp;또는&nbsp;문자&nbsp;메시지로&nbsp;할&nbsp;수&nbsp;있습니다.&nbsp;이용자는&nbsp;회사로부터&nbsp;이메일을&nbsp;통해서나&nbsp;본&nbsp;사이트상&nbsp;공지를&nbsp;통해서&nbsp;본&nbsp;약관이&nbsp;언급하는&nbsp;합의,&nbsp;통지,&nbsp;공개사항&nbsp;및&nbsp;기타&nbsp;통신&nbsp;내용(통칭하여,&nbsp;&apos;통지&apos;)&nbsp;수령함에&nbsp;동의합니다.</p>
<p>②&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;불특정&nbsp;다수&nbsp;회원에&nbsp;대한&nbsp;통지의&nbsp;경우&nbsp;1주일&nbsp;이상&nbsp;서비스&nbsp;사이트&nbsp;내에&nbsp;게시함으로써&nbsp;개별&nbsp;통지에&nbsp;갈음할&nbsp;수&nbsp;있습니다.&nbsp;다만,&nbsp;약관내용의&nbsp;중대한&nbsp;변경이&nbsp;있거나&nbsp;약관이&nbsp;이용자에게&nbsp;불리하게&nbsp;변경되는&nbsp;경우&nbsp;또는&nbsp;회원&nbsp;본인의&nbsp;거래와&nbsp;관련하여&nbsp;중대한&nbsp;영향을&nbsp;미치는&nbsp;사항에&nbsp;대하여는&nbsp;회사는&nbsp;이용자에게&nbsp;이메일&nbsp;또는&nbsp;SMS&nbsp;등을&nbsp;통하여&nbsp;개별적으로&nbsp;통지합니다.</p>
<p>③&nbsp;이용자는&nbsp;회사가&nbsp;이용자에게&nbsp;전자적으로&nbsp;제공하는&nbsp;모든&nbsp;통지는&nbsp;그러한&nbsp;통지가&nbsp;서면으로&nbsp;이루어져야&nbsp;한다는&nbsp;법적&nbsp;요건을&nbsp;충족한다는&nbsp;점에&nbsp;대하여&nbsp;동의합니다.&nbsp;전자적&nbsp;통지&nbsp;수령에&nbsp;대한&nbsp;동의를&nbsp;철회하려면,&nbsp;고객지원실의&nbsp;이메일을&nbsp;통해&nbsp;그와&nbsp;같은&nbsp;동의&nbsp;철회를&nbsp;회사측에&nbsp;통지하여야&nbsp;하고,&nbsp;본&nbsp;사이트&nbsp;이용을&nbsp;중단하여야&nbsp;합니다.</p>
<p>이&nbsp;경우,&nbsp;본&nbsp;약관&nbsp;제15조에&nbsp;정의된&nbsp;제한적&nbsp;이용허락을&nbsp;포함하여,&nbsp;본&nbsp;약관에&nbsp;따라&nbsp;이용자에게&nbsp;부여된&nbsp;모든&nbsp;권리는&nbsp;자동적으로&nbsp;해지됩니다.&nbsp;회사는&nbsp;전자적&nbsp;통지&nbsp;수령에&nbsp;동의하지&nbsp;않는&nbsp;이용자에게&nbsp;본&nbsp;사이트의&nbsp;혜택을&nbsp;제공할&nbsp;수&nbsp;없습니다.</p>
<p>&nbsp;</p>
<p>제31조&nbsp;서비스의&nbsp;제공&nbsp;및&nbsp;변경</p>
<p>①&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;이용자에게&nbsp;아래와&nbsp;같은&nbsp;서비스를&nbsp;제공합니다.</p>
<p>제품의&nbsp;판매</p>
<p>다양한&nbsp;정보의&nbsp;제공</p>
<p>광고,&nbsp;이벤트&nbsp;행사&nbsp;등&nbsp;제품과&nbsp;관련한&nbsp;다양한&nbsp;판촉&nbsp;행위&nbsp;(DM,&nbsp;E-DM&nbsp;및&nbsp;SMS&nbsp;등&nbsp;포함)</p>
<p>기타&nbsp;이용자에게&nbsp;유용한&nbsp;부가&nbsp;서비스</p>
<p>②&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;제품&nbsp;품절&nbsp;등으로&nbsp;더&nbsp;이상&nbsp;제공할&nbsp;수&nbsp;없는&nbsp;경우에는&nbsp;장차&nbsp;체결되는&nbsp;계약에&nbsp;의해&nbsp;제공할&nbsp;제품의&nbsp;내용을&nbsp;변경할&nbsp;수&nbsp;있습니다.</p>
<p>③&nbsp;Mood&nbsp;Ritual&nbsp;몰이&nbsp;제공하기로&nbsp;계약을&nbsp;체결한&nbsp;서비스의&nbsp;내용을&nbsp;제품&nbsp;품절의&nbsp;사유로&nbsp;변경할&nbsp;경우에는&nbsp;그&nbsp;사유를&nbsp;이용자에게&nbsp;등록된&nbsp;전화,&nbsp;이메일&nbsp;혹은&nbsp;SMS&nbsp;등을&nbsp;통해&nbsp;알립니다.</p>
<p>&nbsp;</p>
<p>제32조&nbsp;서비스의&nbsp;중단</p>
<p>①&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;컴퓨터&nbsp;등&nbsp;전기통신설비의&nbsp;보수점검&nbsp;교체&nbsp;및&nbsp;고장,&nbsp;통신의&nbsp;두절&nbsp;등의&nbsp;사유가&nbsp;발생한&nbsp;경우에는&nbsp;서비스의&nbsp;제공을&nbsp;일시적으로&nbsp;중단할&nbsp;수&nbsp;있습니다.</p>
<p>②&nbsp;제1항에&nbsp;의한&nbsp;서비스&nbsp;중단의&nbsp;경우에는&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;고객이&nbsp;등록한&nbsp;통지가능&nbsp;수단&nbsp;중&nbsp;하나를&nbsp;사용하게&nbsp;되며&nbsp;고객의&nbsp;변경&nbsp;및&nbsp;부재로&nbsp;인한&nbsp;미확인으로&nbsp;인해&nbsp;발생된&nbsp;문제에&nbsp;대해서&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;책임지지&nbsp;않습니다.</p>
<p>③&nbsp;사업종목의&nbsp;전환,&nbsp;사업의&nbsp;포기,&nbsp;업체&nbsp;간의&nbsp;통합&nbsp;등의&nbsp;이유로&nbsp;서비스를&nbsp;제공할&nbsp;수&nbsp;없게&nbsp;되는&nbsp;경우에는&nbsp;이를&nbsp;이용자에게&nbsp;통지하고&nbsp;이용자가&nbsp;입은&nbsp;손해에&nbsp;대하여&nbsp;배상합니다.</p>
<p>&nbsp;</p>
<p>제33조&nbsp;회원&nbsp;가입</p>
<p>①&nbsp;이용자는&nbsp;Mood&nbsp;Ritual&nbsp;몰이&nbsp;정한&nbsp;가입&nbsp;양식에&nbsp;따라&nbsp;회원&nbsp;정보를&nbsp;기입한&nbsp;후,&nbsp;이용&nbsp;약관에&nbsp;동의한다는&nbsp;의사&nbsp;표시를&nbsp;함으로써&nbsp;회원&nbsp;가입을&nbsp;신청합니다.</p>
<p>②&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;전항과&nbsp;같이&nbsp;회원으로&nbsp;가입할&nbsp;것을&nbsp;신청한&nbsp;자가&nbsp;다음&nbsp;각&nbsp;호에&nbsp;해당하지&nbsp;않는&nbsp;한&nbsp;신청한&nbsp;자를&nbsp;회원으로&nbsp;등록합니다.</p>
<p>등록&nbsp;내용에&nbsp;허위,&nbsp;기재누락,&nbsp;오기가&nbsp;있는&nbsp;경우</p>
<p>기타&nbsp;회원으로&nbsp;등록하는&nbsp;것이&nbsp;Mood&nbsp;Ritual&nbsp;몰의&nbsp;기술상&nbsp;현저히&nbsp;지장이&nbsp;있다고&nbsp;판단되는&nbsp;경우</p>
<p>③&nbsp;만14세&nbsp;미만의&nbsp;아동은&nbsp;Mood&nbsp;Ritual&nbsp;몰&nbsp;회원가입과&nbsp;전자상거래&nbsp;등&nbsp;계약에&nbsp;관한&nbsp;서비스가&nbsp;제한됩니다.</p>
<p>④&nbsp;회원&nbsp;가입&nbsp;계약의&nbsp;성립시기는&nbsp;Mood&nbsp;Ritual&nbsp;몰의&nbsp;승낙이&nbsp;가입&nbsp;신청자에게&nbsp;도달한&nbsp;시점으로&nbsp;합니다.</p>
<p>⑤&nbsp;회원은&nbsp;Mood&nbsp;Ritual&nbsp;몰에&nbsp;등록한&nbsp;회원정보에&nbsp;변경이&nbsp;있는&nbsp;경우,&nbsp;즉시&nbsp;Mood&nbsp;Ritual&nbsp;몰에서&nbsp;정하는&nbsp;방법에&nbsp;따라&nbsp;해당&nbsp;변경사항을&nbsp;Mood&nbsp;Ritual&nbsp;몰에게&nbsp;통지하거나&nbsp;수정하여야&nbsp;합니다.</p>
<p>&nbsp;</p>
<p>제34조&nbsp;회원의&nbsp;탈퇴&nbsp;및&nbsp;회원자격&nbsp;상실</p>
<p>①&nbsp;회원은&nbsp;Mood&nbsp;Ritual&nbsp;몰에&nbsp;언제든지&nbsp;자신의&nbsp;회원&nbsp;등록을&nbsp;말소해&nbsp;줄&nbsp;것(회원&nbsp;탈퇴)을&nbsp;요청할&nbsp;수&nbsp;있으며&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;위&nbsp;요청을&nbsp;받은&nbsp;해당&nbsp;이용자의&nbsp;회원&nbsp;등록&nbsp;말소를&nbsp;위한&nbsp;절차를&nbsp;밟습니다.&nbsp;단,&nbsp;절차가&nbsp;진행되는&nbsp;동안에는&nbsp;기존&nbsp;일정에&nbsp;맞춰&nbsp;예정된&nbsp;서비스를&nbsp;제공받을&nbsp;수&nbsp;있습니다.</p>
<p>②&nbsp;이용자가&nbsp;다음&nbsp;각&nbsp;호의&nbsp;사유에&nbsp;해당하는&nbsp;경우,&nbsp;Mood&nbsp;Ritual&nbsp;몰은&nbsp;별도의&nbsp;공지&nbsp;없이&nbsp;즉시&nbsp;이용자의&nbsp;회원자격을&nbsp;상실&nbsp;시킬&nbsp;수&nbsp;있습니다.</p>
<p>가입&nbsp;신청&nbsp;시에&nbsp;허위&nbsp;내용을&nbsp;등록한&nbsp;경우</p>
<p>Mood&nbsp;Ritual&nbsp;몰을&nbsp;이용하여&nbsp;구입한&nbsp;재화&nbsp;등의&nbsp;대금,&nbsp;기타&nbsp;서비스&nbsp;이용에&nbsp;관련하여&nbsp;회원이&nbsp;부담하는&nbsp;채무를&nbsp;기일에&nbsp;지급하지&nbsp;않는&nbsp;경우</p>
<p>다른&nbsp;사람의&nbsp;서비스&nbsp;이용을&nbsp;방해하거나&nbsp;그&nbsp;정보를&nbsp;도용하는&nbsp;등&nbsp;전자&nbsp;거래&nbsp;질서를&nbsp;위협하는&nbsp;경우</p>
<p>Mood&nbsp;Ritual&nbsp;몰을&nbsp;이용하여&nbsp;법령과&nbsp;본&nbsp;약관이&nbsp;금지하거나&nbsp;미풍&nbsp;양속에&nbsp;반하는&nbsp;행위를&nbsp;하는&nbsp;경우</p>
<p>③&nbsp;Mood&nbsp;Ritual&nbsp;몰이&nbsp;회원자격을&nbsp;상실&nbsp;시키는&nbsp;경우에는&nbsp;회원등록을&nbsp;말소합니다.&nbsp;이&nbsp;경우&nbsp;회원에게&nbsp;이를&nbsp;통지하고&nbsp;회원등록&nbsp;말소&nbsp;전에&nbsp;최소한&nbsp;30일&nbsp;이상의&nbsp;기간을&nbsp;정하여&nbsp;소명할&nbsp;기회를&nbsp;부여합니다.</p>
<p>&nbsp;</p>
<p>제35조&nbsp;일반조항</p>
<p>①&nbsp;이용자는&nbsp;이용자의&nbsp;본&nbsp;사이트&nbsp;사용과&nbsp;관련하여&nbsp;본&nbsp;약관이&nbsp;회사와&nbsp;이용자&nbsp;간의&nbsp;완전하고&nbsp;배타적인&nbsp;합의를&nbsp;구성하며,&nbsp;이전의&nbsp;모든&nbsp;제안,&nbsp;계약&nbsp;또는&nbsp;기타&nbsp;의견을&nbsp;대체하고&nbsp;규율한다는&nbsp;점에&nbsp;대하여&nbsp;인정하고&nbsp;동의합니다.&nbsp;회사는&nbsp;회사의&nbsp;재량&nbsp;하에&nbsp;본&nbsp;사이트에&nbsp;수정&nbsp;사항을&nbsp;게시함으로써&nbsp;언제든지&nbsp;본&nbsp;약관을&nbsp;수정할&nbsp;권리를&nbsp;가집니다.&nbsp;다만,&nbsp;약관내용의&nbsp;중대한&nbsp;변경이&nbsp;있거나&nbsp;약관이&nbsp;이용자에게&nbsp;불리하게&nbsp;변경되는&nbsp;경우&nbsp;회사는&nbsp;이용자에게&nbsp;이메일&nbsp;또는&nbsp;SMS&nbsp;등을&nbsp;통하여&nbsp;개별적으로&nbsp;통지합니다.</p>
<p>②&nbsp;수정사항&nbsp;공지&nbsp;또는&nbsp;통지&nbsp;이후&nbsp;이용자의&nbsp;계속적인&nbsp;본&nbsp;사이트&nbsp;이용은&nbsp;본&nbsp;약관의&nbsp;모든&nbsp;변경된&nbsp;사항에&nbsp;대한&nbsp;동의를&nbsp;구성합니다.&nbsp;회사는,&nbsp;사전&nbsp;통지를&nbsp;통하여&nbsp;본&nbsp;약관에&nbsp;의하여&nbsp;부여된&nbsp;권리를&nbsp;해지할&nbsp;수&nbsp;있습니다.&nbsp;이용자는&nbsp;본&nbsp;사이트의&nbsp;사용을&nbsp;모두&nbsp;중단함으로써,&nbsp;즉시&nbsp;모든&nbsp;해지&nbsp;또는&nbsp;관련&nbsp;통지를&nbsp;준수하여야&nbsp;합니다.&nbsp;본&nbsp;약관에&nbsp;포함된&nbsp;어떠한&nbsp;사항도&nbsp;회사와&nbsp;이용자&nbsp;간에&nbsp;대리관계,&nbsp;파트너쉽,&nbsp;또는&nbsp;기타&nbsp;형태의&nbsp;합작기업을&nbsp;형성하는&nbsp;것으로&nbsp;해석될&nbsp;수&nbsp;없습니다.</p>
<p>③&nbsp;본&nbsp;약관의&nbsp;어떠한&nbsp;조항이&nbsp;관련&nbsp;법률상&nbsp;이행&nbsp;불가능하거나&nbsp;유효하지&nbsp;않을&nbsp;경우,&nbsp;또는&nbsp;중재판정이나&nbsp;법원의&nbsp;판결을&nbsp;통해&nbsp;이행&nbsp;불가능하거나&nbsp;유효하지&nbsp;않은&nbsp;것으로&nbsp;결정될&nbsp;경우,&nbsp;그와&nbsp;같은&nbsp;이행&nbsp;불가능성이나&nbsp;무효성은&nbsp;본&nbsp;약관&nbsp;전체의&nbsp;이행가능성이나&nbsp;유효성을&nbsp;박탈할&nbsp;수&nbsp;없으나,&nbsp;본&nbsp;약관은&nbsp;재판당국에&nbsp;의하여&nbsp;가능한&nbsp;범위&nbsp;내에서&nbsp;원&nbsp;조항에&nbsp;반영된&nbsp;바와&nbsp;같이&nbsp;당사자들의&nbsp;원래&nbsp;의도를&nbsp;최대한&nbsp;반영하기&nbsp;위하여&nbsp;수정될&nbsp;수&nbsp;있습니다.&nbsp;본&nbsp;약관과&nbsp;관련하여&nbsp;의문사항이&nbsp;있을&nbsp;경우,&nbsp;회사로&nbsp;유선으로&nbsp;연락&nbsp;바랍니다.</p>
<p>&nbsp;</p>
<p>제36조&nbsp;(기타&nbsp;조항)</p>
<p>①&nbsp;회사는&nbsp;필요한&nbsp;경우&nbsp;특정&nbsp;서비스나&nbsp;기능의&nbsp;전부&nbsp;또는&nbsp;일부를&nbsp;Mood&nbsp;Ritual&nbsp;몰을&nbsp;통해&nbsp;일시적&nbsp;또는&nbsp;영구적으로&nbsp;수정하거나&nbsp;중단할&nbsp;수&nbsp;있습니다.</p>
<p>②&nbsp;각&nbsp;당사자는&nbsp;상대방의&nbsp;서면동의&nbsp;없이&nbsp;이&nbsp;약관상의&nbsp;권리와&nbsp;의무를&nbsp;제3자에게&nbsp;양도하거나&nbsp;처분할&nbsp;수&nbsp;없습니다.</p>
<p>③&nbsp;이&nbsp;약관과&nbsp;관련하여&nbsp;당사자간의&nbsp;합의에&nbsp;의하여&nbsp;추가로&nbsp;작성된&nbsp;계약서,&nbsp;협정서,&nbsp;통보서&nbsp;등과&nbsp;회사의&nbsp;정책변경,&nbsp;법령의&nbsp;제개정&nbsp;또는&nbsp;공공기관의&nbsp;고시나&nbsp;지침&nbsp;등에&nbsp;의하여&nbsp;회사가&nbsp;Mood&nbsp;Ritual&nbsp;몰을&nbsp;통해&nbsp;공지하는&nbsp;내용도&nbsp;이용계약의&nbsp;일부를&nbsp;구성합니다.</p>
<p>④ 회사는 구매자 회원이 서비스 이용 시 발생 할 수 있는 정당한 의견이나 불만 사항의 적극적 수렴, 그의 해결, 회원 상호간에 분쟁 조정을 위하여 &ldquo;고객센터&rdquo;를 설치하고 운영합니다. 회사는 회원이 제기하는 각종 불만사항 및 의견에 대하여 적극적으로 검토 후 정당하다고 판단되는 경우 이를 신속하게 처리하며, 즉시 처리가 곤란한 사항에 대하여서는 그 사유와 처리기간에 대하여 e-mail 혹은 전화를 통하여 회원에게 통보를 합니다.</p>