<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<c:set var="ctp" value="${pageContext.request.contextPath}"/>
<p>제1조(목적)</p>
<p>이&nbsp;약관은&nbsp;Mood&nbsp;Ritual(이하&nbsp;&ldquo;MR&rdquo;이라&nbsp;한다)이&nbsp;운영하는&nbsp;Mood&nbsp;Ritual&nbsp;몰(이하&nbsp;&ldquo;몰&rdquo;이라&nbsp;한다)에서&nbsp;제공하는&nbsp;인터넷&nbsp;관련&nbsp;서비스(이하&nbsp;&ldquo;서비스&rdquo;라&nbsp;한다)를&nbsp;이용함에&nbsp;있어&nbsp;사이버&nbsp;몰과&nbsp;이용자의&nbsp;권리,&nbsp;의무&nbsp;및&nbsp;책임사항을&nbsp;규정함을&nbsp;목적으로&nbsp;합니다.</p>
<p>※「PC통신,&nbsp;무선&nbsp;등을&nbsp;이용하는&nbsp;전자상거래에&nbsp;대해서도&nbsp;그&nbsp;성질에&nbsp;반하지&nbsp;않는&nbsp;한&nbsp;이&nbsp;약관을&nbsp;준용합니다」</p>
<p>제2조(정의)</p>
<p>①&ldquo;몰&rdquo;&nbsp;이란&nbsp;MR이&nbsp;재화&nbsp;또는&nbsp;용역(이하&nbsp;&ldquo;재화등&rdquo;이라&nbsp;함)을&nbsp;이용자에게&nbsp;제공하기&nbsp;위하여&nbsp;컴퓨터등&nbsp;정보통신설비를&nbsp;이용하여&nbsp;재화등을&nbsp;거래할&nbsp;수&nbsp;있도록&nbsp;설정한&nbsp;가상의&nbsp;영업장을&nbsp;말하며,&nbsp;아울러&nbsp;사이버몰을&nbsp;운영하는&nbsp;사업자의&nbsp;의미로도&nbsp;사용합니다.</p>
<p>②&ldquo;이용자&rdquo;란&nbsp;&ldquo;몰&rdquo;에&nbsp;접속하여&nbsp;이&nbsp;약관에&nbsp;따라&nbsp;&ldquo;몰&rdquo;이&nbsp;제공하는&nbsp;서비스를&nbsp;받는&nbsp;회원&nbsp;및&nbsp;비회원을&nbsp;말합니다.</p>
<p>③&nbsp;&lsquo;회원&rsquo;이라&nbsp;함은&nbsp;&ldquo;몰&rdquo;에&nbsp;개인정보를&nbsp;제공하여&nbsp;회원등록을&nbsp;한&nbsp;자로서,&nbsp;&ldquo;몰&rdquo;의&nbsp;정보를&nbsp;지속적으로&nbsp;제공받으며,&nbsp;&ldquo;몰&rdquo;이&nbsp;제공하는&nbsp;서비스를&nbsp;계속적으로&nbsp;이용할&nbsp;수&nbsp;있는&nbsp;자를&nbsp;말합니다.</p>
<p>④&nbsp;&lsquo;비회원&rsquo;이라&nbsp;함은&nbsp;회원에&nbsp;가입하지&nbsp;않고&nbsp;&ldquo;몰&rdquo;이&nbsp;제공하는&nbsp;서비스를&nbsp;이용하는&nbsp;자를&nbsp;말합니다.</p>
<p>제3조&nbsp;(약관등의&nbsp;명시와&nbsp;설명&nbsp;및&nbsp;개정)</p>
<p>①&nbsp;&ldquo;몰&rdquo;은&nbsp;이&nbsp;약관의&nbsp;내용과&nbsp;상호&nbsp;및&nbsp;대표자&nbsp;성명,&nbsp;영업소&nbsp;소재지&nbsp;주소(소비자의&nbsp;불만을&nbsp;처리할&nbsp;수&nbsp;있는&nbsp;곳의&nbsp;주소를&nbsp;포함),&nbsp;전화번호,&nbsp;모사전송번호,&nbsp;전자우편주소,&nbsp;사업자등록번호,&nbsp;통신판매업신고번호,&nbsp;개인정보관리책임자등을&nbsp;이용자가&nbsp;쉽게&nbsp;알&nbsp;수&nbsp;있도록&nbsp;&ldquo;몰&rdquo;의&nbsp;초기&nbsp;서비스화면(전면)에&nbsp;게시합니다.&nbsp;다만,&nbsp;약관의&nbsp;내용은&nbsp;이용자가&nbsp;연결화면을&nbsp;통하여&nbsp;볼&nbsp;수&nbsp;있도록&nbsp;할&nbsp;수&nbsp;있습니다.</p>
<p>②&nbsp;&ldquo;몰은&nbsp;이용자가&nbsp;약관에&nbsp;동의하기에&nbsp;앞서&nbsp;약관에&nbsp;정하여져&nbsp;있는&nbsp;내용&nbsp;중&nbsp;청약철회,&nbsp;배송책임,&nbsp;환불조건&nbsp;등과&nbsp;같은&nbsp;중요한&nbsp;내용을&nbsp;이용자가&nbsp;이해할&nbsp;수&nbsp;있도록&nbsp;별도의&nbsp;연결화면&nbsp;또는&nbsp;팝업화면&nbsp;등을&nbsp;제공하여&nbsp;이용자의&nbsp;확인을&nbsp;구하여야&nbsp;합니다.</p>
<p>③&nbsp;&ldquo;몰&rdquo;은&nbsp;전자상거래&nbsp;등에서의&nbsp;소비자보호에&nbsp;관한&nbsp;법률,&nbsp;약관의&nbsp;규제에&nbsp;관한&nbsp;법률,&nbsp;전자거래기본법,&nbsp;전자서명법,&nbsp;정보통신망&nbsp;이용촉진등에&nbsp;관한&nbsp;법률,&nbsp;방문판매등에&nbsp;관한&nbsp;법률,&nbsp;소비자보호법&nbsp;등&nbsp;관련법을&nbsp;위배하지&nbsp;않는&nbsp;범위에서&nbsp;이&nbsp;약관을&nbsp;개정할&nbsp;수&nbsp;있습니다.</p>
<p>④&nbsp;&ldquo;몰&rdquo;이&nbsp;약관을&nbsp;개정할&nbsp;경우에는&nbsp;적용일자&nbsp;및&nbsp;개정사유를&nbsp;명시하여&nbsp;현행약관과&nbsp;함께&nbsp;몰의&nbsp;초기화면에&nbsp;그&nbsp;적용일자&nbsp;7일&nbsp;이전부터&nbsp;적용일자&nbsp;전일까지&nbsp;공지합니다.</p>
<p>다만,&nbsp;이용자에게&nbsp;불리하게&nbsp;약관내용을&nbsp;변경하는&nbsp;경우에는&nbsp;최소한&nbsp;30일&nbsp;이상의&nbsp;사전&nbsp;유예기간을&nbsp;두고&nbsp;공지합니다.&nbsp;이&nbsp;경우&nbsp;&quot;몰&ldquo;은&nbsp;개정&nbsp;전&nbsp;내용과&nbsp;개정&nbsp;후&nbsp;내용을&nbsp;명확하게&nbsp;비교하여&nbsp;이용자가&nbsp;알기&nbsp;쉽도록&nbsp;표시합니다.</p>
<p>⑤&nbsp;&ldquo;몰&rdquo;이&nbsp;약관을&nbsp;개정할&nbsp;경우에는&nbsp;그&nbsp;개정약관은&nbsp;그&nbsp;적용일자&nbsp;이후에&nbsp;체결되는&nbsp;계약에만&nbsp;적용되고&nbsp;그&nbsp;이전에&nbsp;이미&nbsp;체결된&nbsp;계약에&nbsp;대해서는&nbsp;개정전의&nbsp;약관조항이&nbsp;그대로&nbsp;적용됩니다.&nbsp;다만&nbsp;이미&nbsp;계약을&nbsp;체결한&nbsp;이용자가&nbsp;개정약관&nbsp;조항의&nbsp;적용을&nbsp;받기를&nbsp;원하는&nbsp;뜻을&nbsp;제3항에&nbsp;의한&nbsp;개정약관의&nbsp;공지기간내에&nbsp;&lsquo;몰&ldquo;에&nbsp;송신하여&nbsp;&rdquo;몰&ldquo;의&nbsp;동의를&nbsp;받은&nbsp;경우에는&nbsp;개정약관&nbsp;조항이&nbsp;적용됩니다.</p>
<p>⑥&nbsp;이&nbsp;약관에서&nbsp;정하지&nbsp;아니한&nbsp;사항과&nbsp;이&nbsp;약관의&nbsp;해석에&nbsp;관하여는&nbsp;전자상거래등에서의&nbsp;소비자&nbsp;보호에&nbsp;관한&nbsp;법률,&nbsp;약관의&nbsp;규제등에&nbsp;관한&nbsp;법률,&nbsp;공정거래위원회가&nbsp;정하는&nbsp;전자상거래등에서의&nbsp;소비자&nbsp;보호지침&nbsp;및&nbsp;관계법령&nbsp;또는&nbsp;상관례에&nbsp;따릅니다.</p>
<p>제4조(서비스의&nbsp;제공&nbsp;및&nbsp;변경)</p>
<p>①&nbsp;&ldquo;몰&rdquo;은&nbsp;다음과&nbsp;같은&nbsp;업무를&nbsp;수행합니다.</p>
<p>1.&nbsp;재화&nbsp;또는&nbsp;용역에&nbsp;대한&nbsp;정보&nbsp;제공&nbsp;및&nbsp;구매계약의&nbsp;체결</p>
<p>2.&nbsp;구매계약이&nbsp;체결된&nbsp;재화&nbsp;또는&nbsp;용역의&nbsp;배송</p>
<p>3.&nbsp;기타&nbsp;&ldquo;몰&rdquo;이&nbsp;정하는&nbsp;업무</p>
<p>②&ldquo;몰&rdquo;은&nbsp;재화&nbsp;또는&nbsp;용역의&nbsp;품절&nbsp;또는&nbsp;기술적&nbsp;사양의&nbsp;변경&nbsp;등의&nbsp;경우에는&nbsp;장차&nbsp;체결되는&nbsp;계약에&nbsp;의해&nbsp;제공할&nbsp;재화&nbsp;또는&nbsp;용역의&nbsp;내용을&nbsp;변경할&nbsp;수&nbsp;있습니다.&nbsp;이&nbsp;경우에는&nbsp;변경된&nbsp;재화&nbsp;또는&nbsp;용역의&nbsp;내용&nbsp;및&nbsp;제공일자를&nbsp;명시하여&nbsp;현재의&nbsp;재화&nbsp;또는&nbsp;용역의&nbsp;내용을&nbsp;게시한&nbsp;곳에&nbsp;즉시&nbsp;공지합니다.</p>
<p>③&ldquo;몰&rdquo;이&nbsp;제공하기로&nbsp;이용자와&nbsp;계약을&nbsp;체결한&nbsp;서비스의&nbsp;내용을&nbsp;재화등의&nbsp;품절&nbsp;또는&nbsp;기술적&nbsp;사양의&nbsp;변경&nbsp;등의&nbsp;사유로&nbsp;변경할&nbsp;경우에는&nbsp;그&nbsp;사유를&nbsp;이용자에게&nbsp;통지&nbsp;가능한&nbsp;주소로&nbsp;즉시&nbsp;통지합니다.</p>
<p>④전항의&nbsp;경우&nbsp;&ldquo;몰&rdquo;은&nbsp;이로&nbsp;인하여&nbsp;이용자가&nbsp;입은&nbsp;손해를&nbsp;배상합니다.&nbsp;다만,&nbsp;&ldquo;몰&rdquo;이&nbsp;고의&nbsp;또는&nbsp;과실이&nbsp;없음을&nbsp;입증하는&nbsp;경우에는&nbsp;그러하지&nbsp;아니합니다.</p>
<p>제5조(서비스의&nbsp;중단)</p>
<p>①&nbsp;&ldquo;몰&rdquo;은&nbsp;컴퓨터&nbsp;등&nbsp;정보통신설비의&nbsp;보수점검,&nbsp;교체&nbsp;및&nbsp;고장,&nbsp;통신의&nbsp;두절&nbsp;등의&nbsp;사유가&nbsp;발생한&nbsp;경우에는&nbsp;서비스의&nbsp;제공을&nbsp;일시적으로&nbsp;중단할&nbsp;수&nbsp;있습니다.</p>
<p>②&ldquo;몰&rdquo;은&nbsp;제1항의&nbsp;사유로&nbsp;서비스의&nbsp;제공이&nbsp;일시적으로&nbsp;중단됨으로&nbsp;인하여&nbsp;이용자&nbsp;또는&nbsp;제3자가&nbsp;입은&nbsp;손해에&nbsp;대하여&nbsp;배상합니다.&nbsp;단,&nbsp;&ldquo;몰&rdquo;이&nbsp;고의&nbsp;또는&nbsp;과실이&nbsp;없음을&nbsp;입증하는&nbsp;경우에는&nbsp;그러하지&nbsp;아니합니다.</p>
<p>③사업종목의&nbsp;전환,&nbsp;사업의&nbsp;포기,&nbsp;업체간의&nbsp;통합&nbsp;등의&nbsp;이유로&nbsp;서비스를&nbsp;제공할&nbsp;수&nbsp;없게&nbsp;되는&nbsp;경우에는&nbsp;&ldquo;몰&rdquo;은&nbsp;제8조에&nbsp;정한&nbsp;방법으로&nbsp;이용자에게&nbsp;통지하고&nbsp;당초&nbsp;&ldquo;몰&rdquo;에서&nbsp;제시한&nbsp;조건에&nbsp;따라&nbsp;소비자에게&nbsp;보상합니다.&nbsp;다만,&nbsp;&ldquo;몰&rdquo;이&nbsp;보상기준&nbsp;등을&nbsp;고지하지&nbsp;아니한&nbsp;경우에는&nbsp;이용자들의&nbsp;마일리지&nbsp;또는&nbsp;적립금&nbsp;등을&nbsp;&ldquo;몰&rdquo;에서&nbsp;통용되는&nbsp;통화가치에&nbsp;상응하는&nbsp;현물&nbsp;또는&nbsp;현금으로&nbsp;이용자에게&nbsp;지급합니다.</p>
<p>제6조(회원가입)</p>
<p>①&nbsp;이용자는&nbsp;&ldquo;몰&rdquo;이&nbsp;정한&nbsp;가입&nbsp;양식에&nbsp;따라&nbsp;회원정보를&nbsp;기입한&nbsp;후&nbsp;이&nbsp;약관에&nbsp;동의한다는&nbsp;의사표시를&nbsp;함으로서&nbsp;회원가입을&nbsp;신청합니다.</p>
<p>②&nbsp;&ldquo;몰&rdquo;은&nbsp;제1항과&nbsp;같이&nbsp;회원으로&nbsp;가입할&nbsp;것을&nbsp;신청한&nbsp;이용자&nbsp;중&nbsp;다음&nbsp;각&nbsp;호에&nbsp;해당하지&nbsp;않는&nbsp;한&nbsp;회원으로&nbsp;등록합니다.</p>
<p>1.&nbsp;가입신청자가&nbsp;이&nbsp;약관&nbsp;제7조제3항에&nbsp;의하여&nbsp;이전에&nbsp;회원자격을&nbsp;상실한&nbsp;적이&nbsp;있는&nbsp;경우,&nbsp;다만&nbsp;제7조제3항에&nbsp;의한&nbsp;회원자격&nbsp;상실&nbsp;후&nbsp;3년이&nbsp;경과한&nbsp;자로서&nbsp;&ldquo;몰&rdquo;의&nbsp;회원재가입&nbsp;승낙을&nbsp;얻은&nbsp;경우에는&nbsp;예외로&nbsp;한다.</p>
<p>2.&nbsp;등록&nbsp;내용에&nbsp;허위,&nbsp;기재누락,&nbsp;오기가&nbsp;있는&nbsp;경우</p>
<p>3.&nbsp;기타&nbsp;회원으로&nbsp;등록하는&nbsp;것이&nbsp;&ldquo;몰&rdquo;의&nbsp;기술상&nbsp;현저히&nbsp;지장이&nbsp;있다고&nbsp;판단되는&nbsp;경우</p>
<p>③&nbsp;회원가입계약의&nbsp;성립시기는&nbsp;&ldquo;몰&rdquo;의&nbsp;승낙이&nbsp;회원에게&nbsp;도달한&nbsp;시점으로&nbsp;합니다.</p>
<p>④&nbsp;회원은&nbsp;제15조제1항에&nbsp;의한&nbsp;등록사항에&nbsp;변경이&nbsp;있는&nbsp;경우,&nbsp;즉시&nbsp;전자우편&nbsp;기타&nbsp;방법으로&nbsp;&ldquo;몰&rdquo;에&nbsp;대하여&nbsp;그&nbsp;변경사항을&nbsp;알려야&nbsp;합니다.</p>
<p>제7조(회원&nbsp;탈퇴&nbsp;및&nbsp;자격&nbsp;상실&nbsp;등)</p>
<p>①&nbsp;회원은&nbsp;&ldquo;몰&rdquo;에&nbsp;언제든지&nbsp;탈퇴를&nbsp;요청할&nbsp;수&nbsp;있으며&nbsp;&ldquo;몰&rdquo;은&nbsp;즉시&nbsp;회원탈퇴를&nbsp;처리합니다.</p>
<p>②&nbsp;회원이&nbsp;다음&nbsp;각&nbsp;호의&nbsp;사유에&nbsp;해당하는&nbsp;경우,&nbsp;&ldquo;몰&rdquo;은&nbsp;회원자격을&nbsp;제한&nbsp;및&nbsp;정지시킬&nbsp;수&nbsp;있습니다.</p>
<p>1.&nbsp;가입&nbsp;신청시에&nbsp;허위&nbsp;내용을&nbsp;등록한&nbsp;경우</p>
<p>2.&nbsp;&ldquo;몰&rdquo;을&nbsp;이용하여&nbsp;구입한&nbsp;재화등의&nbsp;대금,&nbsp;기타&nbsp;&ldquo;몰&rdquo;이용에&nbsp;관련하여&nbsp;회원이&nbsp;부담하는&nbsp;채무를&nbsp;기일에&nbsp;지급하지&nbsp;않는&nbsp;경우</p>
<p>3.&nbsp;다른&nbsp;사람의&nbsp;&ldquo;몰&rdquo;&nbsp;이용을&nbsp;방해하거나&nbsp;그&nbsp;정보를&nbsp;도용하는&nbsp;등&nbsp;전자상거래&nbsp;질서를&nbsp;위협하는&nbsp;경우</p>
<p>4.&nbsp;&ldquo;몰&rdquo;을&nbsp;이용하여&nbsp;법령&nbsp;또는&nbsp;이&nbsp;약관이&nbsp;금지하거나&nbsp;공서양속에&nbsp;반하는&nbsp;행위를&nbsp;하는&nbsp;경우</p>
<p>③&nbsp;&ldquo;몰&rdquo;이&nbsp;회원&nbsp;자격을&nbsp;제한,&nbsp;정지&nbsp;시킨&nbsp;후,&nbsp;동일한&nbsp;행위가&nbsp;2회&nbsp;이상&nbsp;반복되거나&nbsp;30일&nbsp;이내에&nbsp;그&nbsp;사유가&nbsp;시정되지&nbsp;아니하는&nbsp;경우&nbsp;&ldquo;몰&rdquo;은&nbsp;회원자격을&nbsp;상실시킬&nbsp;수&nbsp;있습니다.</p>
<p>④&nbsp;&ldquo;몰&rdquo;이&nbsp;회원자격을&nbsp;상실시키는&nbsp;경우에는&nbsp;회원등록을&nbsp;말소합니다.&nbsp;이&nbsp;경우&nbsp;회원에게&nbsp;이를&nbsp;통지하고,&nbsp;회원등록&nbsp;말소&nbsp;전에&nbsp;최소한&nbsp;30일&nbsp;이상의&nbsp;기간을&nbsp;정하여&nbsp;소명할&nbsp;기회를&nbsp;부여합니다.</p>
<p>제8조(회원에&nbsp;대한&nbsp;통지)</p>
<p>①&nbsp;&ldquo;몰&rdquo;이&nbsp;회원에&nbsp;대한&nbsp;통지를&nbsp;하는&nbsp;경우,&nbsp;회원이&nbsp;&ldquo;몰&rdquo;과&nbsp;미리&nbsp;약정하여&nbsp;지정한&nbsp;전자우편&nbsp;주소로&nbsp;할&nbsp;수&nbsp;있습니다.</p>
<p>②&nbsp;&ldquo;몰&rdquo;은&nbsp;불특정다수&nbsp;회원에&nbsp;대한&nbsp;통지의&nbsp;경우&nbsp;1주일이상&nbsp;&ldquo;몰&rdquo;&nbsp;게시판에&nbsp;게시함으로서&nbsp;개별&nbsp;통지에&nbsp;갈음할&nbsp;수&nbsp;있습니다.&nbsp;다만,&nbsp;회원&nbsp;본인의&nbsp;거래와&nbsp;관련하여&nbsp;중대한&nbsp;영향을&nbsp;미치는&nbsp;사항에&nbsp;대하여는&nbsp;개별통지를&nbsp;합니다.</p>
<p>제9조(구매신청)</p>
<p>&ldquo;몰&rdquo;이용자는&nbsp;&ldquo;몰&rdquo;상에서&nbsp;다음&nbsp;또는&nbsp;이와&nbsp;유사한&nbsp;방법에&nbsp;의하여&nbsp;구매를&nbsp;신청하며,&nbsp;&ldquo;몰&rdquo;은&nbsp;이용자가&nbsp;구매신청을&nbsp;함에&nbsp;있어서&nbsp;다음의&nbsp;각&nbsp;내용을&nbsp;알기&nbsp;쉽게&nbsp;제공하여야&nbsp;합니다.&nbsp;단,&nbsp;회원인&nbsp;경우&nbsp;제2호&nbsp;내지&nbsp;제4호의&nbsp;적용을&nbsp;제외할&nbsp;수&nbsp;있습니다.</p>
<p>1.&nbsp;재화등의&nbsp;검색&nbsp;및&nbsp;선택</p>
<p>2.&nbsp;성명,&nbsp;주소,&nbsp;전화번호,&nbsp;전자우편주소(또는&nbsp;이동전화번호)&nbsp;등의&nbsp;입력</p>
<p>3.&nbsp;약관내용,&nbsp;청약철회권이&nbsp;제한되는&nbsp;서비스,&nbsp;배송료,&nbsp;설치비&nbsp;등의&nbsp;비용부담과&nbsp;관련한&nbsp;내용에&nbsp;대한&nbsp;확인</p>
<p>4.&nbsp;이&nbsp;약관에&nbsp;동의하고&nbsp;위&nbsp;3.호의&nbsp;사항을&nbsp;확인하거나&nbsp;거부하는&nbsp;표시(예,&nbsp;마우스&nbsp;클릭)</p>
<p>5.&nbsp;재화등의&nbsp;구매신청&nbsp;및&nbsp;이에&nbsp;관한&nbsp;확인&nbsp;또는&nbsp;&ldquo;몰&rdquo;의&nbsp;확인에&nbsp;대한&nbsp;동의</p>
<p>6.&nbsp;결제방법의&nbsp;선택</p>
<p>제10조&nbsp;(계약의&nbsp;성립)</p>
<p>①&nbsp;&ldquo;몰&rdquo;은&nbsp;제9조와&nbsp;같은&nbsp;구매신청에&nbsp;대하여&nbsp;다음&nbsp;각&nbsp;호에&nbsp;해당하면&nbsp;승낙하지&nbsp;않을&nbsp;수&nbsp;있습니다.&nbsp;다만,&nbsp;미성년자와&nbsp;계약을&nbsp;체결하는&nbsp;경우에는&nbsp;법정대리인의&nbsp;동의를&nbsp;얻지&nbsp;못하면&nbsp;미성년자&nbsp;본인&nbsp;또는&nbsp;법정대리인이&nbsp;계약을&nbsp;취소할&nbsp;수&nbsp;있다는&nbsp;내용을&nbsp;고지하여야&nbsp;합니다.</p>
<p>1.&nbsp;신청&nbsp;내용에&nbsp;허위,&nbsp;기재누락,&nbsp;오기가&nbsp;있는&nbsp;경우</p>
<p>2.&nbsp;미성년자가&nbsp;담배,&nbsp;주류등&nbsp;청소년보호법에서&nbsp;금지하는&nbsp;재화&nbsp;및&nbsp;용역을&nbsp;구매하는&nbsp;경우</p>
<p>3.&nbsp;기타&nbsp;구매신청에&nbsp;승낙하는&nbsp;것이&nbsp;&ldquo;몰&rdquo;&nbsp;기술상&nbsp;현저히&nbsp;지장이&nbsp;있다고&nbsp;판단하는&nbsp;경우</p>
<p>②&nbsp;&ldquo;몰&rdquo;의&nbsp;승낙이&nbsp;제12조제1항의&nbsp;수신확인통지형태로&nbsp;이용자에게&nbsp;도달한&nbsp;시점에&nbsp;계약이&nbsp;성립한&nbsp;것으로&nbsp;봅니다.</p>
<p>③&nbsp;&ldquo;몰&rdquo;의&nbsp;승낙의&nbsp;의사표시에는&nbsp;이용자의&nbsp;구매&nbsp;신청에&nbsp;대한&nbsp;확인&nbsp;및&nbsp;판매가능&nbsp;여부,&nbsp;구매신청의&nbsp;정정&nbsp;취소등에&nbsp;관한&nbsp;정보등을&nbsp;포함하여야&nbsp;합니다.</p>
<p>제11조(지급방법)</p>
<p>&ldquo;몰&rdquo;에서&nbsp;구매한&nbsp;재화&nbsp;또는&nbsp;용역에&nbsp;대한&nbsp;대금지급방법은&nbsp;다음&nbsp;각&nbsp;호의&nbsp;방법&nbsp;중&nbsp;가용한&nbsp;방법으로&nbsp;할&nbsp;수&nbsp;있습니다.&nbsp;단,&nbsp;&ldquo;몰&rdquo;은&nbsp;이용자의&nbsp;지급방법에&nbsp;대하여&nbsp;재화&nbsp;등의&nbsp;대금에&nbsp;어떠한&nbsp;명목의&nbsp;수수료도&nbsp;추가하여&nbsp;징수할&nbsp;수&nbsp;없습니다.</p>
<p>1.&nbsp;폰뱅킹,&nbsp;인터넷뱅킹,&nbsp;메일&nbsp;뱅킹&nbsp;등의&nbsp;각종&nbsp;계좌이체</p>
<p>2.&nbsp;선불카드,&nbsp;직불카드,&nbsp;신용카드&nbsp;등의&nbsp;각종&nbsp;카드&nbsp;결제</p>
<p>3.&nbsp;온라인&nbsp;무통장&nbsp;입금</p>
<p>4.&nbsp;전자화폐에&nbsp;의한&nbsp;결제</p>
<p>5.&nbsp;수령&nbsp;시&nbsp;대금지급</p>
<p>6.&nbsp;마일리지&nbsp;등&nbsp;&ldquo;몰&rdquo;이&nbsp;지급한&nbsp;포인트에&nbsp;의한&nbsp;결제</p>
<p>7.&nbsp;&ldquo;몰&rdquo;과&nbsp;계약을&nbsp;맺었거나&nbsp;&ldquo;몰&rdquo;이&nbsp;인정한&nbsp;상품권에&nbsp;의한&nbsp;결제</p>
<p>8.&nbsp;기타&nbsp;전자적&nbsp;지급&nbsp;방법에&nbsp;의한&nbsp;대금&nbsp;지급&nbsp;등</p>
<p>제12조(수신확인통지,&nbsp;구매신청&nbsp;변경&nbsp;및&nbsp;취소)</p>
<p>①&nbsp;&ldquo;몰&rdquo;은&nbsp;이용자의&nbsp;구매신청이&nbsp;있는&nbsp;경우&nbsp;이용자에게&nbsp;수신확인통지를&nbsp;합니다.</p>
<p>②&nbsp;수신확인통지를&nbsp;받은&nbsp;이용자는&nbsp;의사표시의&nbsp;불일치등이&nbsp;있는&nbsp;경우에는&nbsp;수신확인통지를&nbsp;받은&nbsp;후&nbsp;즉시&nbsp;구매신청&nbsp;변경&nbsp;및&nbsp;취소를&nbsp;요청할&nbsp;수&nbsp;있고&nbsp;&ldquo;몰&rdquo;은&nbsp;배송전에&nbsp;이용자의&nbsp;요청이&nbsp;있는&nbsp;경우에는&nbsp;지체없이&nbsp;그&nbsp;요청에&nbsp;따라&nbsp;처리하여야&nbsp;합니다.&nbsp;다만&nbsp;이미&nbsp;대금을&nbsp;지불한&nbsp;경우에는&nbsp;제15조의&nbsp;청약철회&nbsp;등에&nbsp;관한&nbsp;규정에&nbsp;따릅니다.</p>
<p>제13조(재화등의&nbsp;공급)</p>
<p>①&nbsp;&ldquo;몰&rdquo;은&nbsp;이용자와&nbsp;재화등의&nbsp;공급시기에&nbsp;관하여&nbsp;별도의&nbsp;약정이&nbsp;없는&nbsp;이상,&nbsp;이용자가&nbsp;청약을&nbsp;한&nbsp;날부터&nbsp;7일&nbsp;이내에&nbsp;재화&nbsp;등을&nbsp;배송할&nbsp;수&nbsp;있도록&nbsp;주문제작,&nbsp;포장&nbsp;등&nbsp;기타의&nbsp;필요한&nbsp;조치를&nbsp;취합니다.&nbsp;다만,&nbsp;&ldquo;몰&rdquo;이&nbsp;이미&nbsp;재화&nbsp;등의&nbsp;대금의&nbsp;전부&nbsp;또는&nbsp;일부를&nbsp;받은&nbsp;경우에는&nbsp;대금의&nbsp;전부&nbsp;또는&nbsp;일부를&nbsp;받은&nbsp;날부터&nbsp;2영업일&nbsp;이내에&nbsp;조치를&nbsp;취합니다.&nbsp;이때&nbsp;&ldquo;몰&rdquo;은&nbsp;이용자가&nbsp;재화등의&nbsp;공급&nbsp;절차&nbsp;및&nbsp;진행&nbsp;사항을&nbsp;확인할&nbsp;수&nbsp;있도록&nbsp;적절한&nbsp;조치를&nbsp;합니다.</p>
<p>②&ldquo;몰&rdquo;은&nbsp;이용자가&nbsp;구매한&nbsp;재화에&nbsp;대해&nbsp;배송수단,&nbsp;수단별&nbsp;배송비용&nbsp;부담자,&nbsp;수단별&nbsp;배송기간&nbsp;등을&nbsp;명시합니다.&nbsp;만약&nbsp;&ldquo;몰&rdquo;이&nbsp;약정&nbsp;배송기간을&nbsp;초과한&nbsp;경우에는&nbsp;그로&nbsp;인한&nbsp;이용자의&nbsp;손해를&nbsp;배상하여야&nbsp;합니다.&nbsp;다만&nbsp;&ldquo;몰&rdquo;이&nbsp;고의,&nbsp;과실이&nbsp;없음을&nbsp;입증한&nbsp;경우에는&nbsp;그러하지&nbsp;아니합니다.</p>
<p>제14조(환급)</p>
<p>&ldquo;몰&rdquo;은&nbsp;이용자가&nbsp;구매신청한&nbsp;재화등이&nbsp;품절&nbsp;등의&nbsp;사유로&nbsp;인도&nbsp;또는&nbsp;제공을&nbsp;할&nbsp;수&nbsp;없을&nbsp;때에는&nbsp;지체없이&nbsp;그&nbsp;사유를&nbsp;이용자에게&nbsp;통지하고&nbsp;사전에&nbsp;재화&nbsp;등의&nbsp;대금을&nbsp;받은&nbsp;경우에는&nbsp;대금을&nbsp;받은&nbsp;날부터&nbsp;2영업일&nbsp;이내에&nbsp;환급하거나&nbsp;환급에&nbsp;필요한&nbsp;조치를&nbsp;취합니다.</p>
<p>제15조(청약철회&nbsp;등)</p>
<p>①&ldquo;몰&rdquo;과&nbsp;재화등의&nbsp;구매에&nbsp;관한&nbsp;계약을&nbsp;체결한&nbsp;이용자는&nbsp;수신확인의&nbsp;통지를&nbsp;받은&nbsp;날부터&nbsp;7일&nbsp;이내에는&nbsp;청약의&nbsp;철회를&nbsp;할&nbsp;수&nbsp;있습니다.</p>
<p>②&nbsp;이용자는&nbsp;재화등을&nbsp;배송받은&nbsp;경우&nbsp;다음&nbsp;각호의&nbsp;1에&nbsp;해당하는&nbsp;경우에는&nbsp;반품&nbsp;및&nbsp;교환을&nbsp;할&nbsp;수&nbsp;없습니다.</p>
<p>1.&nbsp;이용자에게&nbsp;책임&nbsp;있는&nbsp;사유로&nbsp;재화&nbsp;등이&nbsp;멸실&nbsp;또는&nbsp;훼손된&nbsp;경우(다만,&nbsp;재화&nbsp;등의&nbsp;내용을&nbsp;확인하기&nbsp;위하여&nbsp;포장&nbsp;등을&nbsp;훼손한&nbsp;경우에는&nbsp;청약철회를&nbsp;할&nbsp;수&nbsp;있습니다)</p>
<p>2.&nbsp;이용자의&nbsp;사용&nbsp;또는&nbsp;일부&nbsp;소비에&nbsp;의하여&nbsp;재화&nbsp;등의&nbsp;가치가&nbsp;현저히&nbsp;감소한&nbsp;경우</p>
<p>3.&nbsp;시간의&nbsp;경과에&nbsp;의하여&nbsp;재판매가&nbsp;곤란할&nbsp;정도로&nbsp;재화등의&nbsp;가치가&nbsp;현저히&nbsp;감소한&nbsp;경우</p>
<p>4.&nbsp;같은&nbsp;성능을&nbsp;지닌&nbsp;재화등으로&nbsp;복제가&nbsp;가능한&nbsp;경우&nbsp;그&nbsp;원본인&nbsp;재화&nbsp;등의&nbsp;포장을&nbsp;훼손한&nbsp;경우</p>
<p>③&nbsp;제2항제2호&nbsp;내지&nbsp;제4호의&nbsp;경우에&nbsp;&ldquo;몰&rdquo;이&nbsp;사전에&nbsp;청약철회&nbsp;등이&nbsp;제한되는&nbsp;사실을&nbsp;소비자가&nbsp;쉽게&nbsp;알&nbsp;수&nbsp;있는&nbsp;곳에&nbsp;명기하거나&nbsp;시용상품을&nbsp;제공하는&nbsp;등의&nbsp;조치를&nbsp;하지&nbsp;않았다면&nbsp;이용자의&nbsp;청약철회등이&nbsp;제한되지&nbsp;않습니다.</p>
<p>④&nbsp;이용자는&nbsp;제1항&nbsp;및&nbsp;제2항의&nbsp;규정에&nbsp;불구하고&nbsp;재화등의&nbsp;내용이&nbsp;표시&middot;광고&nbsp;내용과&nbsp;다르거나&nbsp;계약내용과&nbsp;다르게&nbsp;이행된&nbsp;때에는&nbsp;당해&nbsp;재화등을&nbsp;공급받은&nbsp;날부터&nbsp;3월이내,&nbsp;그&nbsp;사실을&nbsp;안&nbsp;날&nbsp;또는&nbsp;알&nbsp;수&nbsp;있었던&nbsp;날부터&nbsp;30일&nbsp;이내에&nbsp;청약철회&nbsp;등을&nbsp;할&nbsp;수&nbsp;있습니다.</p>
<p>제16조(청약철회&nbsp;등의&nbsp;효과)</p>
<p>①&nbsp;&ldquo;몰&rdquo;은&nbsp;이용자로부터&nbsp;재화&nbsp;등을&nbsp;반환받은&nbsp;경우&nbsp;3영업일&nbsp;이내에&nbsp;이미&nbsp;지급받은&nbsp;재화등의&nbsp;대금을&nbsp;환급합니다.&nbsp;이&nbsp;경우&nbsp;&ldquo;몰&rdquo;이&nbsp;이용자에게&nbsp;재화등의&nbsp;환급을&nbsp;지연한&nbsp;때에는&nbsp;그&nbsp;지연기간에&nbsp;대하여&nbsp;공정거래위원회가&nbsp;정하여&nbsp;고시하는&nbsp;지연이자율을&nbsp;곱하여&nbsp;산정한&nbsp;지연이자를&nbsp;지급합니다.</p>
<p>②&nbsp;&ldquo;몰&rdquo;은&nbsp;위&nbsp;대금을&nbsp;환급함에&nbsp;있어서&nbsp;이용자가&nbsp;신용카드&nbsp;또는&nbsp;전자화폐&nbsp;등의&nbsp;결제수단으로&nbsp;재화등의&nbsp;대금을&nbsp;지급한&nbsp;때에는&nbsp;지체없이&nbsp;당해&nbsp;결제수단을&nbsp;제공한&nbsp;사업자로&nbsp;하여금&nbsp;재화등의&nbsp;대금의&nbsp;청구를&nbsp;정지&nbsp;또는&nbsp;취소하도록&nbsp;요청합니다.</p>
<p>③&nbsp;청약철회등의&nbsp;경우&nbsp;공급받은&nbsp;재화등의&nbsp;반환에&nbsp;필요한&nbsp;비용은&nbsp;이용자가&nbsp;부담합니다.&nbsp;&ldquo;몰&rdquo;은&nbsp;이용자에게&nbsp;청약철회등을&nbsp;이유로&nbsp;위약금&nbsp;또는&nbsp;손해배상을&nbsp;청구하지&nbsp;않습니다.&nbsp;다만&nbsp;재화등의&nbsp;내용이&nbsp;표시&middot;광고&nbsp;내용과&nbsp;다르거나&nbsp;계약내용과&nbsp;다르게&nbsp;이행되어&nbsp;청약철회등을&nbsp;하는&nbsp;경우&nbsp;재화등의&nbsp;반환에&nbsp;필요한&nbsp;비용은&nbsp;&ldquo;몰&rdquo;이&nbsp;부담합니다.</p>
<p>④&nbsp;이용자가&nbsp;재화등을&nbsp;제공받을때&nbsp;발송비를&nbsp;부담한&nbsp;경우에&nbsp;&ldquo;몰&rdquo;은&nbsp;청약철회시&nbsp;그&nbsp;비용을&nbsp;누가&nbsp;부담하는지를&nbsp;이용자가&nbsp;알기&nbsp;쉽도록&nbsp;명확하게&nbsp;표시합니다.</p>
<p>제17조(개인정보보호)</p>
<p>①&ldquo;몰&rdquo;은&nbsp;이용자의&nbsp;정보수집시&nbsp;구매계약&nbsp;이행에&nbsp;필요한&nbsp;최소한의&nbsp;정보를&nbsp;수집합니다.&nbsp;다음&nbsp;사항을&nbsp;필수사항으로&nbsp;하며&nbsp;그&nbsp;외&nbsp;사항은&nbsp;선택사항으로&nbsp;합니다.</p>
<p>1.&nbsp;성명</p>
<p>2.&nbsp;주민등록번호(회원의&nbsp;경우)&nbsp;또는&nbsp;외국인등록번호</p>
<p>3.&nbsp;주소</p>
<p>4.&nbsp;전화번호</p>
<p>5.&nbsp;희망ID(회원의&nbsp;경우)</p>
<p>6.&nbsp;비밀번호(회원의&nbsp;경우)</p>
<p>7.&nbsp;전자우편주소(또는&nbsp;이동전화번호)</p>
<p>②&nbsp;&ldquo;몰&rdquo;이&nbsp;이용자의&nbsp;개인식별이&nbsp;가능한&nbsp;개인정보를&nbsp;수집하는&nbsp;때에는&nbsp;반드시&nbsp;당해&nbsp;이용자의&nbsp;동의를&nbsp;받습니다.</p>
<p>③제공된&nbsp;개인정보는&nbsp;당해&nbsp;이용자의&nbsp;동의없이&nbsp;목적외의&nbsp;이용이나&nbsp;제3자에게&nbsp;제공할&nbsp;수&nbsp;없으며,&nbsp;이에&nbsp;대한&nbsp;모든&nbsp;책임은&nbsp;　몰　이&nbsp;집니다.&nbsp;다만,&nbsp;다음의&nbsp;경우에는&nbsp;예외로&nbsp;합니다.</p>
<p>1.&nbsp;배송업무상&nbsp;배송업체에게&nbsp;배송에&nbsp;필요한&nbsp;최소한의&nbsp;이용자의&nbsp;정보(성명,&nbsp;주소,&nbsp;전화번호)를&nbsp;알려주는&nbsp;경우</p>
<p>2.&nbsp;통계작성,&nbsp;학술연구&nbsp;또는&nbsp;시장조사를&nbsp;위하여&nbsp;필요한&nbsp;경우로서&nbsp;특정&nbsp;개인을&nbsp;식별할&nbsp;수&nbsp;없는&nbsp;형태로&nbsp;제공하는&nbsp;경우</p>
<p>3.&nbsp;재화등의&nbsp;거래에&nbsp;따른&nbsp;대금정산을&nbsp;위하여&nbsp;필요한&nbsp;경우</p>
<p>4.&nbsp;도용방지를&nbsp;위하여&nbsp;본인확인에&nbsp;필요한&nbsp;경우</p>
<p>5.&nbsp;법률의&nbsp;규정&nbsp;또는&nbsp;법률에&nbsp;의하여&nbsp;필요한&nbsp;불가피한&nbsp;사유가&nbsp;있는&nbsp;경우</p>
<p>④&ldquo;몰&rdquo;이&nbsp;제2항과&nbsp;제3항에&nbsp;의해&nbsp;이용자의&nbsp;동의를&nbsp;받아야&nbsp;하는&nbsp;경우에는&nbsp;개인정보관리&nbsp;책임자의&nbsp;신원(소속,&nbsp;성명&nbsp;및&nbsp;전화번호,&nbsp;기타&nbsp;연락처),&nbsp;정보의&nbsp;수집목적&nbsp;및&nbsp;이용목적,&nbsp;제3자에&nbsp;대한&nbsp;정보제공&nbsp;관련사항(제공받은자,&nbsp;제공목적&nbsp;및&nbsp;제공할&nbsp;정보의&nbsp;내용)&nbsp;등&nbsp;정보통신망&nbsp;이용촉진등에&nbsp;관한법률&nbsp;제22조제2항이&nbsp;규정한&nbsp;사항을&nbsp;미리&nbsp;명시하거나&nbsp;고지해야&nbsp;하며&nbsp;이용자는&nbsp;언제든지&nbsp;이&nbsp;동의를&nbsp;철회할&nbsp;수&nbsp;있습니다.</p>
<p>⑤이용자는&nbsp;언제든지&nbsp;&ldquo;몰&rdquo;이&nbsp;가지고&nbsp;있는&nbsp;자신의&nbsp;개인정보에&nbsp;대해&nbsp;열람&nbsp;및&nbsp;오류정정을&nbsp;요구할&nbsp;수&nbsp;있으며&nbsp;&ldquo;몰&rdquo;은&nbsp;이에&nbsp;대해&nbsp;지체없이&nbsp;필요한&nbsp;조치를&nbsp;취할&nbsp;의무를&nbsp;집니다.&nbsp;이용자가&nbsp;오류의&nbsp;정정을&nbsp;요구한&nbsp;경우에는&nbsp;&ldquo;몰&rdquo;은&nbsp;그&nbsp;오류를&nbsp;정정할&nbsp;때까지&nbsp;당해&nbsp;개인정보를&nbsp;이용하지&nbsp;않습니다.</p>
<p>⑥&nbsp;&ldquo;몰&rdquo;은&nbsp;개인정보&nbsp;보호를&nbsp;위하여&nbsp;관리자를&nbsp;한정하여&nbsp;그&nbsp;수를&nbsp;최소화하며&nbsp;신용카드,&nbsp;은행계좌&nbsp;등을&nbsp;포함한&nbsp;이용자의&nbsp;개인정보의&nbsp;분실,&nbsp;도난,&nbsp;유출,&nbsp;변조&nbsp;등으로&nbsp;인한&nbsp;이용자의&nbsp;손해에&nbsp;대하여&nbsp;모든&nbsp;책임을&nbsp;집니다.</p>
<p>⑦&nbsp;&ldquo;몰&rdquo;&nbsp;또는&nbsp;그로부터&nbsp;개인정보를&nbsp;제공받은&nbsp;제3자는&nbsp;개인정보의&nbsp;수집목적&nbsp;또는&nbsp;제공받은&nbsp;목적을&nbsp;달성한&nbsp;때에는&nbsp;당해&nbsp;개인정보를&nbsp;지체없이&nbsp;파기합니다.</p>
<p>제18조(&ldquo;몰&ldquo;의&nbsp;의무)</p>
<p>①&nbsp;&ldquo;몰&rdquo;은&nbsp;법령과&nbsp;이&nbsp;약관이&nbsp;금지하거나&nbsp;공서양속에&nbsp;반하는&nbsp;행위를&nbsp;하지&nbsp;않으며&nbsp;이&nbsp;약관이&nbsp;정하는&nbsp;바에&nbsp;따라&nbsp;지속적이고,&nbsp;안정적으로&nbsp;재화,&nbsp;용역을&nbsp;제공하는데&nbsp;최선을&nbsp;다하여야&nbsp;합니다.</p>
<p>②&nbsp;&ldquo;몰&rdquo;은&nbsp;이용자가&nbsp;안전하게&nbsp;인터넷&nbsp;서비스를&nbsp;이용할&nbsp;수&nbsp;있도록&nbsp;이용자의&nbsp;개인정보(신용정보&nbsp;포함)보호를&nbsp;위한&nbsp;보안&nbsp;시스템을&nbsp;갖추어야&nbsp;합니다.</p>
<p>③&nbsp;&ldquo;몰&rdquo;이&nbsp;상품이나&nbsp;용역에&nbsp;대하여&nbsp;「표시,&nbsp;광고의&nbsp;공정화에&nbsp;관한법률」&nbsp;제3조&nbsp;소정의&nbsp;부당한&nbsp;표시,&nbsp;광고행위를&nbsp;함으로써&nbsp;이용자가&nbsp;손해를&nbsp;입은&nbsp;때에는&nbsp;이를&nbsp;배상할&nbsp;책임을&nbsp;집니다.</p>
<p>④&nbsp;&ldquo;몰&rdquo;은&nbsp;이용자가&nbsp;원하지&nbsp;않는&nbsp;영리목적의&nbsp;광고성&nbsp;전자우편을&nbsp;발송하지&nbsp;않습니다.</p>
<p>제19조(회원의&nbsp;ID&nbsp;및&nbsp;비밀번호에&nbsp;대한&nbsp;의무)</p>
<p>①&nbsp;제17조의&nbsp;경우를&nbsp;제외한&nbsp;ID와&nbsp;비밀번호에&nbsp;관한&nbsp;관리책임은&nbsp;회원에게&nbsp;있습니다.</p>
<p>②&nbsp;회원은&nbsp;자신의&nbsp;ID&nbsp;및&nbsp;비밀번호를&nbsp;제3자에게&nbsp;이용하게&nbsp;해서는&nbsp;안됩니다.</p>
<p>③&nbsp;회원이&nbsp;자신의&nbsp;ID&nbsp;및&nbsp;비밀번호를&nbsp;도난당하거나&nbsp;제3자가&nbsp;사용하고&nbsp;있음을&nbsp;인지한&nbsp;경우에는&nbsp;바로&nbsp;&ldquo;몰&rdquo;에&nbsp;통보하고&nbsp;&ldquo;몰&rdquo;의&nbsp;안내가&nbsp;있는&nbsp;경우에는&nbsp;그에&nbsp;따라야&nbsp;합니다.</p>
<p>제20조(이용자의&nbsp;의무)</p>
<p>이용자는&nbsp;다음&nbsp;행위를&nbsp;하여서는&nbsp;안됩니다.</p>
<p>1.&nbsp;신청&nbsp;또는&nbsp;변경&nbsp;시&nbsp;허위&nbsp;내용의&nbsp;등록</p>
<p>2.&nbsp;타인의&nbsp;정보&nbsp;도용</p>
<p>3.&nbsp;&ldquo;몰&rdquo;에&nbsp;게시된&nbsp;정보의&nbsp;변경</p>
<p>4.&nbsp;&ldquo;몰&rdquo;이&nbsp;정한&nbsp;정보&nbsp;이외의&nbsp;정보(컴퓨터&nbsp;프로그램&nbsp;등)&nbsp;등의&nbsp;송신&nbsp;또는&nbsp;게시</p>
<p>5.&nbsp;&ldquo;몰&rdquo;&nbsp;기타&nbsp;제3자의&nbsp;저작권&nbsp;등&nbsp;지적재산권에&nbsp;대한&nbsp;침해</p>
<p>6.&nbsp;&ldquo;몰&rdquo;&nbsp;기타&nbsp;제3자의&nbsp;명예를&nbsp;손상시키거나&nbsp;업무를&nbsp;방해하는&nbsp;행위</p>
<p>7.&nbsp;외설&nbsp;또는&nbsp;폭력적인&nbsp;메시지,&nbsp;화상,&nbsp;음성,&nbsp;기타&nbsp;공서양속에&nbsp;반하는&nbsp;정보를&nbsp;몰에&nbsp;공개&nbsp;또는&nbsp;게시하는&nbsp;행위</p>
<p>제21조(연결&ldquo;몰&rdquo;과&nbsp;피연결&ldquo;몰&rdquo;&nbsp;간의&nbsp;관계)</p>
<p>①&nbsp;상위&nbsp;&ldquo;몰&rdquo;과&nbsp;하위&nbsp;&ldquo;몰&rdquo;이&nbsp;하이퍼&nbsp;링크(예:&nbsp;하이퍼&nbsp;링크의&nbsp;대상에는&nbsp;문자,&nbsp;그림&nbsp;및&nbsp;동화상&nbsp;등이&nbsp;포함됨)방식&nbsp;등으로&nbsp;연결된&nbsp;경우,&nbsp;전자를&nbsp;연결&nbsp;&ldquo;몰&rdquo;(웹&nbsp;사이트)이라고&nbsp;하고&nbsp;후자를&nbsp;피연결&nbsp;&ldquo;몰&rdquo;(웹사이트)이라고&nbsp;합니다.</p>
<p>②연결&ldquo;몰&rdquo;은&nbsp;피연결&ldquo;몰&rdquo;이&nbsp;독자적으로&nbsp;제공하는&nbsp;재화등에&nbsp;의하여&nbsp;이용자와&nbsp;행하는&nbsp;거래에&nbsp;대해서&nbsp;보증책임을&nbsp;지지&nbsp;않는다는&nbsp;뜻을&nbsp;연결&ldquo;몰&rdquo;의&nbsp;초기화면&nbsp;또는&nbsp;연결되는&nbsp;시점의&nbsp;팝업화면으로&nbsp;명시한&nbsp;경우에는&nbsp;그&nbsp;거래에&nbsp;대한&nbsp;보증책임을&nbsp;지지&nbsp;않습니다.</p>
<p>제22조(저작권의&nbsp;귀속&nbsp;및&nbsp;이용제한)</p>
<p>①&nbsp;&ldquo;몰&ldquo;이&nbsp;작성한&nbsp;저작물에&nbsp;대한&nbsp;저작권&nbsp;기타&nbsp;지적재산권은&nbsp;&rdquo;몰&ldquo;에&nbsp;귀속합니다.</p>
<p>②&nbsp;이용자는&nbsp;&ldquo;몰&rdquo;을&nbsp;이용함으로써&nbsp;얻은&nbsp;정보&nbsp;중&nbsp;&ldquo;몰&rdquo;에게&nbsp;지적재산권이&nbsp;귀속된&nbsp;정보를&nbsp;&ldquo;몰&rdquo;의&nbsp;사전&nbsp;승낙없이&nbsp;복제,&nbsp;송신,&nbsp;출판,&nbsp;배포,&nbsp;방송&nbsp;기타&nbsp;방법에&nbsp;의하여&nbsp;영리목적으로&nbsp;이용하거나&nbsp;제3자에게&nbsp;이용하게&nbsp;하여서는&nbsp;안됩니다.</p>
<p>③&nbsp;&ldquo;몰&rdquo;은&nbsp;약정에&nbsp;따라&nbsp;이용자에게&nbsp;귀속된&nbsp;저작권을&nbsp;사용하는&nbsp;경우&nbsp;당해&nbsp;이용자에게&nbsp;통보하여야&nbsp;합니다.</p>
<p>제23조(분쟁해결)</p>
<p>①&nbsp;&ldquo;몰&rdquo;은&nbsp;이용자가&nbsp;제기하는&nbsp;정당한&nbsp;의견이나&nbsp;불만을&nbsp;반영하고&nbsp;그&nbsp;피해를&nbsp;보상처리하기&nbsp;위하여&nbsp;피해보상처리기구를&nbsp;설치,&nbsp;운영합니다.</p>
<p>②&nbsp;&ldquo;몰&rdquo;은&nbsp;이용자로부터&nbsp;제출되는&nbsp;불만사항&nbsp;및&nbsp;의견은&nbsp;우선적으로&nbsp;그&nbsp;사항을&nbsp;처리합니다.&nbsp;다만,&nbsp;신속한&nbsp;처리가&nbsp;곤란한&nbsp;경우에는&nbsp;이용자에게&nbsp;그&nbsp;사유와&nbsp;처리일정을&nbsp;즉시&nbsp;통보해&nbsp;드립니다.</p>
<p>③&ldquo;몰&rdquo;과&nbsp;이용자간에&nbsp;발생한&nbsp;전자상거래&nbsp;분쟁과&nbsp;관련하여&nbsp;이용자의&nbsp;피해구제신청이&nbsp;있는&nbsp;경우에는&nbsp;공정거래위원회&nbsp;또는&nbsp;시&middot;도지사가&nbsp;의뢰하는&nbsp;분쟁조정기관의&nbsp;조정에&nbsp;따를&nbsp;수&nbsp;있습니다.</p>
<p>제24조(재판권&nbsp;및&nbsp;준거법)</p>
<p>①&ldquo;몰&rdquo;과&nbsp;이용자간에&nbsp;발생한&nbsp;전자상거래&nbsp;분쟁에&nbsp;관한&nbsp;소송은&nbsp;제소&nbsp;당시의&nbsp;이용자의&nbsp;주소에&nbsp;의하고,&nbsp;주소가&nbsp;없는&nbsp;경우에는&nbsp;거소를&nbsp;관할하는&nbsp;지방법원의&nbsp;전속관할로&nbsp;합니다.&nbsp;다만,&nbsp;제소&nbsp;당시&nbsp;이용자의&nbsp;주소&nbsp;또는&nbsp;거소가&nbsp;분명하지&nbsp;않거나&nbsp;외국&nbsp;거주자의&nbsp;경우에는&nbsp;민사소송법상의&nbsp;관할법원에&nbsp;제기합니다.</p>
<p>②&ldquo;몰&rdquo;과&nbsp;이용자간에&nbsp;제기된&nbsp;전자상거래&nbsp;소송에는&nbsp;한국법을&nbsp;적용합니다.</p>
<p>부 칙(시행일) 이 약관은 2022년 06월 27일부터 시행합니다.</p>